// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: code.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.login5.v3.challenges
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CodeChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Method method { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"code_length")]
        public int CodeLength { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"expires_in")]
        public int ExpiresIn { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"canonical_phone_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CanonicalPhoneNumber { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum Method
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SMS")]
            Sms = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CodeSolution : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Code { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
