// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: hashcash.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.login5.v3.challenges
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HashcashChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"prefix")]
        public byte[] Prefix { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"length")]
        public int Length { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HashcashSolution : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"suffix")]
        public byte[] Suffix { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.WellKnown)]
        public global::System.TimeSpan? Duration { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
