// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: login5.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.login5.v3
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Challenges : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Challenge> challenges { get; } = new global::System.Collections.Generic.List<Challenge>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Challenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hashcash")]
        public global::spotify.login5.v3.challenges.HashcashChallenge Hashcash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"code")]
        public global::spotify.login5.v3.challenges.CodeChallenge Code { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeSolutions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"solutions")]
        public global::System.Collections.Generic.List<ChallengeSolution> Solutions { get; } = new global::System.Collections.Generic.List<ChallengeSolution>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeSolution : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hashcash")]
        public global::spotify.login5.v3.challenges.HashcashSolution Hashcash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"code")]
        public global::spotify.login5.v3.challenges.CodeSolution Code { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"client_info")]
        public ClientInfo ClientInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"login_context")]
        public byte[] LoginContext { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"challenge_solutions")]
        public ChallengeSolutions ChallengeSolutions { get; set; }

        [global::ProtoBuf.ProtoMember(100, Name = @"stored_credential")]
        public global::spotify.login5.v3.credentials.StoredCredential StoredCredential { get; set; }

        [global::ProtoBuf.ProtoMember(101, Name = @"password")]
        public global::spotify.login5.v3.credentials.Password Password { get; set; }

        [global::ProtoBuf.ProtoMember(102, Name = @"facebook_access_token")]
        public global::spotify.login5.v3.credentials.FacebookAccessToken FacebookAccessToken { get; set; }

        [global::ProtoBuf.ProtoMember(103, Name = @"phone_number")]
        public global::spotify.login5.v3.identifiers.PhoneNumber PhoneNumber { get; set; }

        [global::ProtoBuf.ProtoMember(104, Name = @"one_time_token")]
        public global::spotify.login5.v3.credentials.OneTimeToken OneTimeToken { get; set; }

        [global::ProtoBuf.ProtoMember(105, Name = @"parent_child_credential")]
        public global::spotify.login5.v3.credentials.ParentChildCredential ParentChildCredential { get; set; }

        [global::ProtoBuf.ProtoMember(106, Name = @"apple_sign_in_credential")]
        public global::spotify.login5.v3.credentials.AppleSignInCredential AppleSignInCredential { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginOk : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Username { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"access_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccessToken { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"stored_credential")]
        public byte[] StoredCredential { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"access_token_expires_in")]
        public int AccessTokenExpiresIn { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ok")]
        public LoginOk Ok { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error")]
        public LoginError Error { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"challenges")]
        public Challenges Challenges { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public global::System.Collections.Generic.List<Warnings> warnings { get; } = new global::System.Collections.Generic.List<Warnings>();

        [global::ProtoBuf.ProtoMember(5, Name = @"login_context")]
        public byte[] LoginContext { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"identifier_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IdentifierToken { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"user_info")]
        public UserInfo UserInfo { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Warnings
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_WARNING")]
            UnknownWarning = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DEPRECATED_PROTOCOL_VERSION")]
            DeprecatedProtocolVersion = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum LoginError
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_ERROR")]
        UnknownError = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_CREDENTIALS")]
        InvalidCredentials = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BAD_REQUEST")]
        BadRequest = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"UNSUPPORTED_LOGIN_PROTOCOL")]
        UnsupportedLoginProtocol = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TIMEOUT")]
        Timeout = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_IDENTIFIER")]
        UnknownIdentifier = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"TOO_MANY_ATTEMPTS")]
        TooManyAttempts = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_PHONENUMBER")]
        InvalidPhonenumber = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"TRY_AGAIN_LATER")]
        TryAgainLater = 8,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
