// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: user_info.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.login5.v3
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"email")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Email { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"email_verified")]
        public bool EmailVerified { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"birthdate")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Birthdate { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public Gender gender { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"phone_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PhoneNumber { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"phone_number_verified")]
        public bool PhoneNumberVerified { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"email_already_registered")]
        public bool EmailAlreadyRegistered { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Gender
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MALE")]
            Male = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FEMALE")]
            Female = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"NEUTRAL")]
            Neutral = 3,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
