// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: authentication.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Spotify
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientResponseEncrypted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"login_credentials", IsRequired = true)]
        public LoginCredentials LoginCredentials { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"account_creation")]
        [global::System.ComponentModel.DefaultValue(AccountCreation.AccountCreationAlwaysPrompt)]
        public AccountCreation AccountCreation
        {
            get { return __pbn__AccountCreation ?? AccountCreation.AccountCreationAlwaysPrompt; }
            set { __pbn__AccountCreation = value; }
        }
        public bool ShouldSerializeAccountCreation() => __pbn__AccountCreation != null;
        public void ResetAccountCreation() => __pbn__AccountCreation = null;
        private AccountCreation? __pbn__AccountCreation;

        [global::ProtoBuf.ProtoMember(30, Name = @"fingerprint_response")]
        public FingerprintResponseUnion FingerprintResponse { get; set; }

        [global::ProtoBuf.ProtoMember(40, Name = @"peer_ticket")]
        public PeerTicketUnion PeerTicket { get; set; }

        [global::ProtoBuf.ProtoMember(50, Name = @"system_info", IsRequired = true)]
        public SystemInfo SystemInfo { get; set; }

        [global::ProtoBuf.ProtoMember(60, Name = @"platform_model")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlatformModel
        {
            get { return __pbn__PlatformModel ?? ""; }
            set { __pbn__PlatformModel = value; }
        }
        public bool ShouldSerializePlatformModel() => __pbn__PlatformModel != null;
        public void ResetPlatformModel() => __pbn__PlatformModel = null;
        private string __pbn__PlatformModel;

        [global::ProtoBuf.ProtoMember(70, Name = @"version_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VersionString
        {
            get { return __pbn__VersionString ?? ""; }
            set { __pbn__VersionString = value; }
        }
        public bool ShouldSerializeVersionString() => __pbn__VersionString != null;
        public void ResetVersionString() => __pbn__VersionString = null;
        private string __pbn__VersionString;

        [global::ProtoBuf.ProtoMember(80, Name = @"appkey")]
        public LibspotifyAppKey Appkey { get; set; }

        [global::ProtoBuf.ProtoMember(90, Name = @"client_info")]
        public ClientInfo ClientInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginCredentials : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Username
        {
            get { return __pbn__Username ?? ""; }
            set { __pbn__Username = value; }
        }
        public bool ShouldSerializeUsername() => __pbn__Username != null;
        public void ResetUsername() => __pbn__Username = null;
        private string __pbn__Username;

        [global::ProtoBuf.ProtoMember(20, Name = @"typ", IsRequired = true)]
        public AuthenticationType Typ { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"auth_data")]
        public byte[] AuthData
        {
            get { return __pbn__AuthData; }
            set { __pbn__AuthData = value; }
        }
        public bool ShouldSerializeAuthData() => __pbn__AuthData != null;
        public void ResetAuthData() => __pbn__AuthData = null;
        private byte[] __pbn__AuthData;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FingerprintResponseUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"grain")]
        public FingerprintGrainResponse Grain { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"hmac_ripemd")]
        public FingerprintHmacRipemdResponse HmacRipemd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FingerprintGrainResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"encrypted_key", IsRequired = true)]
        public byte[] EncryptedKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FingerprintHmacRipemdResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"hmac", IsRequired = true)]
        public byte[] Hmac { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeerTicketUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"public_key")]
        public PeerTicketPublicKey PublicKey { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"old_ticket")]
        public PeerTicketOld OldTicket { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeerTicketPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"public_key", IsRequired = true)]
        public byte[] PublicKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeerTicketOld : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"peer_ticket", IsRequired = true)]
        public byte[] PeerTicket { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"peer_ticket_signature", IsRequired = true)]
        public byte[] PeerTicketSignature { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SystemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"cpu_family", IsRequired = true)]
        public CpuFamily CpuFamily { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"cpu_subtype")]
        public uint CpuSubtype
        {
            get { return __pbn__CpuSubtype.GetValueOrDefault(); }
            set { __pbn__CpuSubtype = value; }
        }
        public bool ShouldSerializeCpuSubtype() => __pbn__CpuSubtype != null;
        public void ResetCpuSubtype() => __pbn__CpuSubtype = null;
        private uint? __pbn__CpuSubtype;

        [global::ProtoBuf.ProtoMember(30, Name = @"cpu_ext")]
        public uint CpuExt
        {
            get { return __pbn__CpuExt.GetValueOrDefault(); }
            set { __pbn__CpuExt = value; }
        }
        public bool ShouldSerializeCpuExt() => __pbn__CpuExt != null;
        public void ResetCpuExt() => __pbn__CpuExt = null;
        private uint? __pbn__CpuExt;

        [global::ProtoBuf.ProtoMember(40, Name = @"brand")]
        [global::System.ComponentModel.DefaultValue(Brand.BrandUnbranded)]
        public Brand Brand
        {
            get { return __pbn__Brand ?? Brand.BrandUnbranded; }
            set { __pbn__Brand = value; }
        }
        public bool ShouldSerializeBrand() => __pbn__Brand != null;
        public void ResetBrand() => __pbn__Brand = null;
        private Brand? __pbn__Brand;

        [global::ProtoBuf.ProtoMember(50, Name = @"brand_flags")]
        public uint BrandFlags
        {
            get { return __pbn__BrandFlags.GetValueOrDefault(); }
            set { __pbn__BrandFlags = value; }
        }
        public bool ShouldSerializeBrandFlags() => __pbn__BrandFlags != null;
        public void ResetBrandFlags() => __pbn__BrandFlags = null;
        private uint? __pbn__BrandFlags;

        [global::ProtoBuf.ProtoMember(60, Name = @"os", IsRequired = true)]
        public Os Os { get; set; }

        [global::ProtoBuf.ProtoMember(70, Name = @"os_version")]
        public uint OsVersion
        {
            get { return __pbn__OsVersion.GetValueOrDefault(); }
            set { __pbn__OsVersion = value; }
        }
        public bool ShouldSerializeOsVersion() => __pbn__OsVersion != null;
        public void ResetOsVersion() => __pbn__OsVersion = null;
        private uint? __pbn__OsVersion;

        [global::ProtoBuf.ProtoMember(80, Name = @"os_ext")]
        public uint OsExt
        {
            get { return __pbn__OsExt.GetValueOrDefault(); }
            set { __pbn__OsExt = value; }
        }
        public bool ShouldSerializeOsExt() => __pbn__OsExt != null;
        public void ResetOsExt() => __pbn__OsExt = null;
        private uint? __pbn__OsExt;

        [global::ProtoBuf.ProtoMember(90, Name = @"system_information_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SystemInformationString
        {
            get { return __pbn__SystemInformationString ?? ""; }
            set { __pbn__SystemInformationString = value; }
        }
        public bool ShouldSerializeSystemInformationString() => __pbn__SystemInformationString != null;
        public void ResetSystemInformationString() => __pbn__SystemInformationString = null;
        private string __pbn__SystemInformationString;

        [global::ProtoBuf.ProtoMember(100, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId
        {
            get { return __pbn__DeviceId ?? ""; }
            set { __pbn__DeviceId = value; }
        }
        public bool ShouldSerializeDeviceId() => __pbn__DeviceId != null;
        public void ResetDeviceId() => __pbn__DeviceId = null;
        private string __pbn__DeviceId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LibspotifyAppKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version", IsRequired = true)]
        public uint Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"devkey", IsRequired = true)]
        public byte[] Devkey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"signature", IsRequired = true)]
        public byte[] Signature { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"useragent", IsRequired = true)]
        public string Useragent { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"callback_hash", IsRequired = true)]
        public byte[] CallbackHash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"limited")]
        public bool Limited
        {
            get { return __pbn__Limited.GetValueOrDefault(); }
            set { __pbn__Limited = value; }
        }
        public bool ShouldSerializeLimited() => __pbn__Limited != null;
        public void ResetLimited() => __pbn__Limited = null;
        private bool? __pbn__Limited;

        [global::ProtoBuf.ProtoMember(2, Name = @"fb")]
        public ClientInfoFacebook Fb { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Language
        {
            get { return __pbn__Language ?? ""; }
            set { __pbn__Language = value; }
        }
        public bool ShouldSerializeLanguage() => __pbn__Language != null;
        public void ResetLanguage() => __pbn__Language = null;
        private string __pbn__Language;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientInfoFacebook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"machine_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MachineId
        {
            get { return __pbn__MachineId ?? ""; }
            set { __pbn__MachineId = value; }
        }
        public bool ShouldSerializeMachineId() => __pbn__MachineId != null;
        public void ResetMachineId() => __pbn__MachineId = null;
        private string __pbn__MachineId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class APWelcome : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"canonical_username", IsRequired = true)]
        public string CanonicalUsername { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"account_type_logged_in", IsRequired = true)]
        public AccountType AccountTypeLoggedIn { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"credentials_type_logged_in", IsRequired = true)]
        public AccountType CredentialsTypeLoggedIn { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"reusable_auth_credentials_type", IsRequired = true)]
        public AuthenticationType ReusableAuthCredentialsType { get; set; }

        [global::ProtoBuf.ProtoMember(40, Name = @"reusable_auth_credentials", IsRequired = true)]
        public byte[] ReusableAuthCredentials { get; set; }

        [global::ProtoBuf.ProtoMember(50, Name = @"lfs_secret")]
        public byte[] LfsSecret
        {
            get { return __pbn__LfsSecret; }
            set { __pbn__LfsSecret = value; }
        }
        public bool ShouldSerializeLfsSecret() => __pbn__LfsSecret != null;
        public void ResetLfsSecret() => __pbn__LfsSecret = null;
        private byte[] __pbn__LfsSecret;

        [global::ProtoBuf.ProtoMember(60, Name = @"account_info")]
        public AccountInfo AccountInfo { get; set; }

        [global::ProtoBuf.ProtoMember(70, Name = @"fb")]
        public AccountInfoFacebook Fb { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"spotify")]
        public AccountInfoSpotify Spotify { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"facebook")]
        public AccountInfoFacebook Facebook { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountInfoSpotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountInfoFacebook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"access_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccessToken
        {
            get { return __pbn__AccessToken ?? ""; }
            set { __pbn__AccessToken = value; }
        }
        public bool ShouldSerializeAccessToken() => __pbn__AccessToken != null;
        public void ResetAccessToken() => __pbn__AccessToken = null;
        private string __pbn__AccessToken;

        [global::ProtoBuf.ProtoMember(2, Name = @"machine_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MachineId
        {
            get { return __pbn__MachineId ?? ""; }
            set { __pbn__MachineId = value; }
        }
        public bool ShouldSerializeMachineId() => __pbn__MachineId != null;
        public void ResetMachineId() => __pbn__MachineId = null;
        private string __pbn__MachineId;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AuthenticationType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHENTICATION_USER_PASS")]
        AuthenticationUserPass = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS")]
        AuthenticationStoredSpotifyCredentials = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHENTICATION_STORED_FACEBOOK_CREDENTIALS")]
        AuthenticationStoredFacebookCredentials = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHENTICATION_SPOTIFY_TOKEN")]
        AuthenticationSpotifyToken = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHENTICATION_FACEBOOK_TOKEN")]
        AuthenticationFacebookToken = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountCreation
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_CREATION_ALWAYS_PROMPT")]
        AccountCreationAlwaysPrompt = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_CREATION_ALWAYS_CREATE")]
        AccountCreationAlwaysCreate = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CpuFamily
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_UNKNOWN")]
        CpuUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_X86")]
        CpuX86 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_X86_64")]
        CpuX8664 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_PPC")]
        CpuPpc = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_PPC_64")]
        CpuPpc64 = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_ARM")]
        CpuArm = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_IA64")]
        CpuIa64 = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_SH")]
        CpuSh = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_MIPS")]
        CpuMips = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"CPU_BLACKFIN")]
        CpuBlackfin = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Brand
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BRAND_UNBRANDED")]
        BrandUnbranded = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BRAND_INQ")]
        BrandInq = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BRAND_HTC")]
        BrandHtc = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"BRAND_NOKIA")]
        BrandNokia = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Os
    {
        [global::ProtoBuf.ProtoEnum(Name = @"OS_UNKNOWN")]
        OsUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_WINDOWS")]
        OsWindows = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_OSX")]
        OsOsx = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_IPHONE")]
        OsIphone = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_S60")]
        OsS60 = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_LINUX")]
        OsLinux = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_WINDOWS_CE")]
        OsWindowsCe = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_ANDROID")]
        OsAndroid = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_PALM")]
        OsPalm = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_FREEBSD")]
        OsFreebsd = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_BLACKBERRY")]
        OsBlackberry = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_SONOS")]
        OsSonos = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_LOGITECH")]
        OsLogitech = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_WP7")]
        OsWp7 = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_ONKYO")]
        OsOnkyo = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_PHILIPS")]
        OsPhilips = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_WD")]
        OsWd = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_VOLVO")]
        OsVolvo = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_TIVO")]
        OsTivo = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_AWOX")]
        OsAwox = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_MEEGO")]
        OsMeego = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_QNXNTO")]
        OsQnxnto = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"OS_BCO")]
        OsBco = 22,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountType
    {
        Spotify = 0,
        Facebook = 1,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
