// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: canvaz-meta.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace com.spotify.canvaz
{

    [global::ProtoBuf.ProtoContract()]
    public enum Type
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IMAGE")]
        Image = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"VIDEO")]
        Video = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_LOOPING")]
        VideoLooping = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"VIDEO_LOOPING_RANDOM")]
        VideoLoopingRandom = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"GIF")]
        Gif = 4,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
