// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: canvaz.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace com.spotify.canvazcache
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Artist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"avatar")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Avatar { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityCanvazResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"canvases")]
        public global::System.Collections.Generic.List<Canvaz> Canvases { get; } = new global::System.Collections.Generic.List<Canvaz>();

        [global::ProtoBuf.ProtoMember(2, Name = @"ttl_in_seconds")]
        public long TtlInSeconds { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Canvaz : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Id { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"url")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Url { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"file_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string FileId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"type")]
            public global::com.spotify.canvaz.Type Type { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"entity_uri")]
            [global::System.ComponentModel.DefaultValue("")]
            public string EntityUri { get; set; } = "";

            [global::ProtoBuf.ProtoMember(6, Name = @"artist")]
            public Artist Artist { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"explicit")]
            public bool Explicit { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"uploaded_by")]
            [global::System.ComponentModel.DefaultValue("")]
            public string UploadedBy { get; set; } = "";

            [global::ProtoBuf.ProtoMember(9, Name = @"etag")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Etag { get; set; } = "";

            [global::ProtoBuf.ProtoMember(11, Name = @"canvas_uri")]
            [global::System.ComponentModel.DefaultValue("")]
            public string CanvasUri { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityCanvazRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entities")]
        public global::System.Collections.Generic.List<Entity> Entities { get; } = new global::System.Collections.Generic.List<Entity>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Entity : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"entity_uri")]
            [global::System.ComponentModel.DefaultValue("")]
            public string EntityUri { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"etag")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Etag { get; set; } = "";

        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
