// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: client_token.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.clienttoken.http.v0
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientTokenRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_type")]
        public ClientTokenRequestType RequestType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"client_data")]
        public ClientDataRequest ClientData
        {
            get { return __pbn__request.Is(2) ? ((ClientDataRequest)__pbn__request.Object) : default; }
            set { __pbn__request = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeClientData() => __pbn__request.Is(2);
        public void ResetClientData() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__request, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__request;

        [global::ProtoBuf.ProtoMember(3, Name = @"challenge_answers")]
        public ChallengeAnswersRequest ChallengeAnswers
        {
            get { return __pbn__request.Is(3) ? ((ChallengeAnswersRequest)__pbn__request.Object) : default; }
            set { __pbn__request = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeChallengeAnswers() => __pbn__request.Is(3);
        public void ResetChallengeAnswers() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__request, 3);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientDataRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"client_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"connectivity_sdk_data")]
        public global::spotify.clienttoken.data.v0.ConnectivitySdkData ConnectivitySdkData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeAnswersRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        [global::System.ComponentModel.DefaultValue("")]
        public string State { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"answers")]
        public global::System.Collections.Generic.List<ChallengeAnswer> Answers { get; } = new global::System.Collections.Generic.List<ChallengeAnswer>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientTokenResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"response_type")]
        public ClientTokenResponseType ResponseType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"granted_token")]
        public GrantedTokenResponse GrantedToken
        {
            get { return __pbn__response.Is(2) ? ((GrantedTokenResponse)__pbn__response.Object) : default; }
            set { __pbn__response = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeGrantedToken() => __pbn__response.Is(2);
        public void ResetGrantedToken() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__response, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__response;

        [global::ProtoBuf.ProtoMember(3, Name = @"challenges")]
        public ChallengesResponse Challenges
        {
            get { return __pbn__response.Is(3) ? ((ChallengesResponse)__pbn__response.Object) : default; }
            set { __pbn__response = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeChallenges() => __pbn__response.Is(3);
        public void ResetChallenges() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__response, 3);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TokenDomain : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GrantedTokenResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"expires_after_seconds")]
        public int ExpiresAfterSeconds { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"refresh_after_seconds")]
        public int RefreshAfterSeconds { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"domains")]
        public global::System.Collections.Generic.List<TokenDomain> Domains { get; } = new global::System.Collections.Generic.List<TokenDomain>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengesResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        [global::System.ComponentModel.DefaultValue("")]
        public string State { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"challenges")]
        public global::System.Collections.Generic.List<Challenge> Challenges { get; } = new global::System.Collections.Generic.List<Challenge>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientSecretParameters : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"salt")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Salt { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EvaluateJSParameters : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Code { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"libraries")]
        public global::System.Collections.Generic.List<string> Libraries { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HashCashParameters : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"length")]
        public int Length { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"prefix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Prefix { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Challenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public ChallengeType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"client_secret_parameters")]
        public ClientSecretParameters ClientSecretParameters
        {
            get { return __pbn__parameters.Is(2) ? ((ClientSecretParameters)__pbn__parameters.Object) : default; }
            set { __pbn__parameters = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeClientSecretParameters() => __pbn__parameters.Is(2);
        public void ResetClientSecretParameters() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__parameters, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__parameters;

        [global::ProtoBuf.ProtoMember(3, Name = @"evaluate_js_parameters")]
        public EvaluateJSParameters EvaluateJsParameters
        {
            get { return __pbn__parameters.Is(3) ? ((EvaluateJSParameters)__pbn__parameters.Object) : default; }
            set { __pbn__parameters = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeEvaluateJsParameters() => __pbn__parameters.Is(3);
        public void ResetEvaluateJsParameters() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__parameters, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"evaluate_hashcash_parameters")]
        public HashCashParameters EvaluateHashcashParameters
        {
            get { return __pbn__parameters.Is(4) ? ((HashCashParameters)__pbn__parameters.Object) : default; }
            set { __pbn__parameters = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeEvaluateHashcashParameters() => __pbn__parameters.Is(4);
        public void ResetEvaluateHashcashParameters() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__parameters, 4);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientSecretHMACAnswer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hmac")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Hmac { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EvaluateJSAnswer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Result { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HashCashAnswer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"suffix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Suffix { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeAnswer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ChallengeType ChallengeType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"client_secret")]
        public ClientSecretHMACAnswer ClientSecret
        {
            get { return __pbn__answer.Is(2) ? ((ClientSecretHMACAnswer)__pbn__answer.Object) : default; }
            set { __pbn__answer = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeClientSecret() => __pbn__answer.Is(2);
        public void ResetClientSecret() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__answer, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__answer;

        [global::ProtoBuf.ProtoMember(3, Name = @"evaluate_js")]
        public EvaluateJSAnswer EvaluateJs
        {
            get { return __pbn__answer.Is(3) ? ((EvaluateJSAnswer)__pbn__answer.Object) : default; }
            set { __pbn__answer = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeEvaluateJs() => __pbn__answer.Is(3);
        public void ResetEvaluateJs() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__answer, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"hash_cash")]
        public HashCashAnswer HashCash
        {
            get { return __pbn__answer.Is(4) ? ((HashCashAnswer)__pbn__answer.Object) : default; }
            set { __pbn__answer = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeHashCash() => __pbn__answer.Is(4);
        public void ResetHashCash() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__answer, 4);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientTokenBadRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public enum ClientTokenRequestType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"REQUEST_UNKNOWN")]
        RequestUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"REQUEST_CLIENT_DATA_REQUEST")]
        RequestClientDataRequest = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"REQUEST_CHALLENGE_ANSWERS_REQUEST")]
        RequestChallengeAnswersRequest = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ClientTokenResponseType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"RESPONSE_UNKNOWN")]
        ResponseUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RESPONSE_GRANTED_TOKEN_RESPONSE")]
        ResponseGrantedTokenResponse = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"RESPONSE_CHALLENGES_RESPONSE")]
        ResponseChallengesResponse = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ChallengeType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CHALLENGE_UNKNOWN")]
        ChallengeUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CHALLENGE_CLIENT_SECRET_HMAC")]
        ChallengeClientSecretHmac = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CHALLENGE_EVALUATE_JS")]
        ChallengeEvaluateJs = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CHALLENGE_HASH_CASH")]
        ChallengeHashCash = 3,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
