// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: connect.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Connectstate
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClusterUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cluster")]
        public Cluster Cluster { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"update_reason")]
        public ClusterUpdateReason UpdateReason { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ack_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AckId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"devices_that_changed")]
        public global::System.Collections.Generic.List<string> DevicesThatChangeds { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Device : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"device_info")]
        public DeviceInfo DeviceInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player_state")]
        public PlayerState PlayerState { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"private_device_info")]
        public PrivateDeviceInfo PrivateDeviceInfo { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"transfer_data")]
        public byte[] TransferData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Cluster : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"active_device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ActiveDeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"player_state")]
        public PlayerState PlayerState { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"device")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, DeviceInfo> Devices { get; } = new global::System.Collections.Generic.Dictionary<string, DeviceInfo>();

        [global::ProtoBuf.ProtoMember(5, Name = @"transfer_data")]
        public byte[] TransferData { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"transfer_data_timestamp")]
        public ulong TransferDataTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"not_playing_since_timestamp")]
        public long NotPlayingSinceTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"need_full_player_state")]
        public bool NeedFullPlayerState { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"server_timestamp_ms")]
        public long ServerTimestampMs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PutStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"callback_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CallbackUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"device")]
        public Device Device { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"member_type")]
        public MemberType MemberType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"is_active")]
        public bool IsActive { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"put_state_reason")]
        public PutStateReason PutStateReason { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"message_id")]
        public uint MessageId { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"last_command_sent_by_device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LastCommandSentByDeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"last_command_message_id")]
        public uint LastCommandMessageId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"started_playing_at")]
        public ulong StartedPlayingAt { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"has_been_playing_for_ms")]
        public ulong HasBeenPlayingForMs { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"client_side_timestamp")]
        public ulong ClientSideTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"only_write_player_state")]
        public bool OnlyWritePlayerState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PrivateDeviceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"platform")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Platform { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"callback_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CallbackUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeviceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"can_play")]
        public bool CanPlay { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"volume")]
        public uint Volume { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"capabilities")]
        public Capabilities Capabilities { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"device_software_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceSoftwareVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"device_type")]
        public DeviceType DeviceType { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"spirc_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SpircVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"is_private_session")]
        public bool IsPrivateSession { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"is_social_connect")]
        public bool IsSocialConnect { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14, Name = @"brand")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Brand { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"model")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Model { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16, Name = @"metadata_map")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> MetadataMaps { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(17, Name = @"product_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProductId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18, Name = @"deduplication_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeduplicationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(19, Name = @"selected_alias_id")]
        public uint SelectedAliasId { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"device_aliases")]
        public global::System.Collections.Generic.List<DeviceAliasesEntry> DeviceAliases { get; } = new global::System.Collections.Generic.List<DeviceAliasesEntry>();

        [global::ProtoBuf.ProtoMember(21, Name = @"is_offline")]
        public bool IsOffline { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"public_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PublicIp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(23, Name = @"license")]
        [global::System.ComponentModel.DefaultValue("")]
        public string License { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public partial class DeviceAliasesEntry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"key")]
            public uint Key { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"value")]
            public DeviceAlias Value { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeviceAlias : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"is_group")]
        public bool IsGroup { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Capabilities : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"can_be_player")]
        public bool CanBePlayer { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"restrict_to_local")]
        public bool RestrictToLocal { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"gaia_eq_connect_id")]
        public bool GaiaEqConnectId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"supports_logout")]
        public bool SupportsLogout { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"is_observable")]
        public bool IsObservable { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"volume_steps")]
        public int VolumeSteps { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"supported_types")]
        public global::System.Collections.Generic.List<string> SupportedTypes { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(10, Name = @"command_acks")]
        public bool CommandAcks { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"supports_rename")]
        public bool SupportsRename { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"hidden")]
        public bool Hidden { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"disable_volume")]
        public bool DisableVolume { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"connect_disabled")]
        public bool ConnectDisabled { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"supports_playlist_v2")]
        public bool SupportsPlaylistV2 { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"is_controllable")]
        public bool IsControllable { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"supports_external_episodes")]
        public bool SupportsExternalEpisodes { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"supports_set_backend_metadata")]
        public bool SupportsSetBackendMetadata { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"supports_transfer_command")]
        public bool SupportsTransferCommand { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"supports_command_request")]
        public bool SupportsCommandRequest { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"is_voice_enabled")]
        public bool IsVoiceEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"needs_full_player_state")]
        public bool NeedsFullPlayerState { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"supports_gzip_pushes")]
        public bool SupportsGzipPushes { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"supports_lossless_audio")]
        public bool SupportsLosslessAudio { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"supports_set_options_command")]
        public bool SupportsSetOptionsCommand { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"supports_hifi")]
        public CapabilitySupportDetails SupportsHifi { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CapabilitySupportDetails : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"fully_supported")]
        public bool FullySupported { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user_eligible")]
        public bool UserEligible { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"device_supported")]
        public bool DeviceSupported { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectCommandOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message_id")]
        public int MessageId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LogoutCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"command_options")]
        public ConnectCommandOptions CommandOptions { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetVolumeCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"volume")]
        public int Volume { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"command_options")]
        public ConnectCommandOptions CommandOptions { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RenameCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rename_to")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RenameTo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"command_options")]
        public ConnectCommandOptions CommandOptions { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetBackendMetadataCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"metadata")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Metadatas { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SendCommandResult
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_SEND_COMMAND_RESULT")]
        UnknownSendCommandResult = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_NOT_FOUND")]
        DeviceNotFound = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CONTEXT_PLAYER_ERROR")]
        ContextPlayerError = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_DISAPPEARED")]
        DeviceDisappeared = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"UPSTREAM_ERROR")]
        UpstreamError = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_DOES_NOT_SUPPORT_COMMAND")]
        DeviceDoesNotSupportCommand = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"RATE_LIMITED")]
        RateLimited = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PutStateReason
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_PUT_STATE_REASON")]
        UnknownPutStateReason = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SPIRC_HELLO")]
        SpircHello = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SPIRC_NOTIFY")]
        SpircNotify = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"NEW_DEVICE")]
        NewDevice = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAYER_STATE_CHANGED")]
        PlayerStateChanged = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"VOLUME_CHANGED")]
        VolumeChanged = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"PICKER_OPENED")]
        PickerOpened = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"BECAME_INACTIVE")]
        BecameInactive = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"ALIAS_CHANGED")]
        AliasChanged = 8,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MemberType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SPIRC_V2")]
        SpircV2 = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SPIRC_V3")]
        SpircV3 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CONNECT_STATE")]
        ConnectState = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CONNECT_STATE_EXTENDED")]
        ConnectStateExtended = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"ACTIVE_DEVICE_TRACKER")]
        ActiveDeviceTracker = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_TOKEN")]
        PlayToken = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ClusterUpdateReason
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_CLUSTER_UPDATE_REASON")]
        UnknownClusterUpdateReason = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICES_DISAPPEARED")]
        DevicesDisappeared = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_STATE_CHANGED")]
        DeviceStateChanged = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"NEW_DEVICE_APPEARED")]
        NewDeviceAppeared = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_VOLUME_CHANGED")]
        DeviceVolumeChanged = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_ALIAS_CHANGED")]
        DeviceAliasChanged = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DeviceType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"COMPUTER")]
        Computer = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TABLET")]
        Tablet = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SMARTPHONE")]
        Smartphone = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SPEAKER")]
        Speaker = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"TV")]
        Tv = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"AVR")]
        Avr = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"STB")]
        Stb = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_DONGLE")]
        AudioDongle = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"GAME_CONSOLE")]
        GameConsole = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"CAST_VIDEO")]
        CastVideo = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"CAST_AUDIO")]
        CastAudio = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTOMOBILE")]
        Automobile = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"SMARTWATCH")]
        Smartwatch = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"CHROMEBOOK")]
        Chromebook = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_SPOTIFY")]
        UnknownSpotify = 100,
        [global::ProtoBuf.ProtoEnum(Name = @"CAR_THING")]
        CarThing = 101,
        [global::ProtoBuf.ProtoEnum(Name = @"OBSERVER")]
        Observer = 102,
        [global::ProtoBuf.ProtoEnum(Name = @"HOME_THING")]
        HomeThing = 103,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
