// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: context_player_options.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.player.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ContextPlayerOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ContextPlayerOptions()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"shuffling_context")]
        public bool ShufflingContext
        {
            get { return __pbn__ShufflingContext.GetValueOrDefault(); }
            set { __pbn__ShufflingContext = value; }
        }
        public bool ShouldSerializeShufflingContext()
        {
            return __pbn__ShufflingContext != null;
        }
        public void ResetShufflingContext()
        {
            __pbn__ShufflingContext = null;
        }
        private bool? __pbn__ShufflingContext;

        [global::ProtoBuf.ProtoMember(2, Name = @"repeating_context")]
        public bool RepeatingContext
        {
            get { return __pbn__RepeatingContext.GetValueOrDefault(); }
            set { __pbn__RepeatingContext = value; }
        }
        public bool ShouldSerializeRepeatingContext()
        {
            return __pbn__RepeatingContext != null;
        }
        public void ResetRepeatingContext()
        {
            __pbn__RepeatingContext = null;
        }
        private bool? __pbn__RepeatingContext;

        [global::ProtoBuf.ProtoMember(3, Name = @"repeating_track")]
        public bool RepeatingTrack
        {
            get { return __pbn__RepeatingTrack.GetValueOrDefault(); }
            set { __pbn__RepeatingTrack = value; }
        }
        public bool ShouldSerializeRepeatingTrack()
        {
            return __pbn__RepeatingTrack != null;
        }
        public void ResetRepeatingTrack()
        {
            __pbn__RepeatingTrack = null;
        }
        private bool? __pbn__RepeatingTrack;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContextPlayerOptionOverrides : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ContextPlayerOptionOverrides()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"shuffling_context")]
        public bool ShufflingContext
        {
            get { return __pbn__ShufflingContext.GetValueOrDefault(); }
            set { __pbn__ShufflingContext = value; }
        }
        public bool ShouldSerializeShufflingContext()
        {
            return __pbn__ShufflingContext != null;
        }
        public void ResetShufflingContext()
        {
            __pbn__ShufflingContext = null;
        }
        private bool? __pbn__ShufflingContext;

        [global::ProtoBuf.ProtoMember(2, Name = @"repeating_context")]
        public bool RepeatingContext
        {
            get { return __pbn__RepeatingContext.GetValueOrDefault(); }
            set { __pbn__RepeatingContext = value; }
        }
        public bool ShouldSerializeRepeatingContext()
        {
            return __pbn__RepeatingContext != null;
        }
        public void ResetRepeatingContext()
        {
            __pbn__RepeatingContext = null;
        }
        private bool? __pbn__RepeatingContext;

        [global::ProtoBuf.ProtoMember(3, Name = @"repeating_track")]
        public bool RepeatingTrack
        {
            get { return __pbn__RepeatingTrack.GetValueOrDefault(); }
            set { __pbn__RepeatingTrack = value; }
        }
        public bool ShouldSerializeRepeatingTrack()
        {
            return __pbn__RepeatingTrack != null;
        }
        public void ResetRepeatingTrack()
        {
            __pbn__RepeatingTrack = null;
        }
        private bool? __pbn__RepeatingTrack;

    }

}

#pragma warning restore 0612, 1591, 3021
