// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: context_track.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.player.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ContextTrack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ContextTrack()
        {
            Metadatas = new global::System.Collections.Generic.Dictionary<string, string>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri
        {
            get { return __pbn__Uri ?? ""; }
            set { __pbn__Uri = value; }
        }
        public bool ShouldSerializeUri()
        {
            return __pbn__Uri != null;
        }
        public void ResetUri()
        {
            __pbn__Uri = null;
        }
        private string __pbn__Uri;

        [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uid
        {
            get { return __pbn__Uid ?? ""; }
            set { __pbn__Uid = value; }
        }
        public bool ShouldSerializeUid()
        {
            return __pbn__Uid != null;
        }
        public void ResetUid()
        {
            __pbn__Uid = null;
        }
        private string __pbn__Uid;

        [global::ProtoBuf.ProtoMember(3, Name = @"gid")]
        public byte[] Gid
        {
            get { return __pbn__Gid; }
            set { __pbn__Gid = value; }
        }
        public bool ShouldSerializeGid()
        {
            return __pbn__Gid != null;
        }
        public void ResetGid()
        {
            __pbn__Gid = null;
        }
        private byte[] __pbn__Gid;

        [global::ProtoBuf.ProtoMember(4, Name = @"metadata")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Metadatas { get; private set; }

    }

}

#pragma warning restore 0612, 1591, 3021
