// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: context_page.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.player.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ContextPage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ContextPage()
        {
            Metadatas = new global::System.Collections.Generic.Dictionary<string, string>();
            Tracks = new global::System.Collections.Generic.List<ContextTrack>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"page_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PageUrl
        {
            get { return __pbn__PageUrl ?? ""; }
            set { __pbn__PageUrl = value; }
        }
        public bool ShouldSerializePageUrl()
        {
            return __pbn__PageUrl != null;
        }
        public void ResetPageUrl()
        {
            __pbn__PageUrl = null;
        }
        private string __pbn__PageUrl;

        [global::ProtoBuf.ProtoMember(2, Name = @"next_page_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NextPageUrl
        {
            get { return __pbn__NextPageUrl ?? ""; }
            set { __pbn__NextPageUrl = value; }
        }
        public bool ShouldSerializeNextPageUrl()
        {
            return __pbn__NextPageUrl != null;
        }
        public void ResetNextPageUrl()
        {
            __pbn__NextPageUrl = null;
        }
        private string __pbn__NextPageUrl;

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Metadatas { get; private set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"tracks")]
        public global::System.Collections.Generic.List<ContextTrack> Tracks { get; private set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"loading")]
        public bool Loading
        {
            get { return __pbn__Loading.GetValueOrDefault(); }
            set { __pbn__Loading = value; }
        }
        public bool ShouldSerializeLoading()
        {
            return __pbn__Loading != null;
        }
        public void ResetLoading()
        {
            __pbn__Loading = null;
        }
        private bool? __pbn__Loading;

    }

}

#pragma warning restore 0612, 1591, 3021
