// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: context.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.player.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Context : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri
        {
            get { return __pbn__Uri ?? ""; }
            set { __pbn__Uri = value; }
        }
        public bool ShouldSerializeUri() => __pbn__Uri != null;
        public void ResetUri() => __pbn__Uri = null;
        private string __pbn__Uri;

        [global::ProtoBuf.ProtoMember(2, Name = @"url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Url
        {
            get { return __pbn__Url ?? ""; }
            set { __pbn__Url = value; }
        }
        public bool ShouldSerializeUrl() => __pbn__Url != null;
        public void ResetUrl() => __pbn__Url = null;
        private string __pbn__Url;

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Metadatas { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"restrictions")]
        public Restrictions Restrictions { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"pages")]
        public global::System.Collections.Generic.List<ContextPage> Pages { get; } = new global::System.Collections.Generic.List<ContextPage>();

        [global::ProtoBuf.ProtoMember(6, Name = @"loading")]
        public bool Loading
        {
            get { return __pbn__Loading.GetValueOrDefault(); }
            set { __pbn__Loading = value; }
        }
        public bool ShouldSerializeLoading() => __pbn__Loading != null;
        public void ResetLoading() => __pbn__Loading = null;
        private bool? __pbn__Loading;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
