// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: entity_extension_data.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.extendedmetadata.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityExtensionDataHeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public EntityExtensionDataHeader()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"status_code")]
        public int StatusCode
        {
            get { return __pbn__StatusCode.GetValueOrDefault(); }
            set { __pbn__StatusCode = value; }
        }
        public bool ShouldSerializeStatusCode()
        {
            return __pbn__StatusCode != null;
        }
        public void ResetStatusCode()
        {
            __pbn__StatusCode = null;
        }
        private int? __pbn__StatusCode;

        [global::ProtoBuf.ProtoMember(2, Name = @"etag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Etag
        {
            get { return __pbn__Etag ?? ""; }
            set { __pbn__Etag = value; }
        }
        public bool ShouldSerializeEtag()
        {
            return __pbn__Etag != null;
        }
        public void ResetEtag()
        {
            __pbn__Etag = null;
        }
        private string __pbn__Etag;

        [global::ProtoBuf.ProtoMember(3, Name = @"locale")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Locale
        {
            get { return __pbn__Locale ?? ""; }
            set { __pbn__Locale = value; }
        }
        public bool ShouldSerializeLocale()
        {
            return __pbn__Locale != null;
        }
        public void ResetLocale()
        {
            __pbn__Locale = null;
        }
        private string __pbn__Locale;

        [global::ProtoBuf.ProtoMember(4, Name = @"cache_ttl_in_seconds")]
        public long CacheTtlInSeconds
        {
            get { return __pbn__CacheTtlInSeconds.GetValueOrDefault(); }
            set { __pbn__CacheTtlInSeconds = value; }
        }
        public bool ShouldSerializeCacheTtlInSeconds()
        {
            return __pbn__CacheTtlInSeconds != null;
        }
        public void ResetCacheTtlInSeconds()
        {
            __pbn__CacheTtlInSeconds = null;
        }
        private long? __pbn__CacheTtlInSeconds;

        [global::ProtoBuf.ProtoMember(5, Name = @"offline_ttl_in_seconds")]
        public long OfflineTtlInSeconds
        {
            get { return __pbn__OfflineTtlInSeconds.GetValueOrDefault(); }
            set { __pbn__OfflineTtlInSeconds = value; }
        }
        public bool ShouldSerializeOfflineTtlInSeconds()
        {
            return __pbn__OfflineTtlInSeconds != null;
        }
        public void ResetOfflineTtlInSeconds()
        {
            __pbn__OfflineTtlInSeconds = null;
        }
        private long? __pbn__OfflineTtlInSeconds;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityExtensionData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public EntityExtensionData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public EntityExtensionDataHeader Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"entity_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EntityUri
        {
            get { return __pbn__EntityUri ?? ""; }
            set { __pbn__EntityUri = value; }
        }
        public bool ShouldSerializeEntityUri()
        {
            return __pbn__EntityUri != null;
        }
        public void ResetEntityUri()
        {
            __pbn__EntityUri = null;
        }
        private string __pbn__EntityUri;
    }

}

#pragma warning restore 0612, 1591, 3021
