// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: explicit_content_pubsub.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.explicitcontent.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyValuePair : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public KeyValuePair()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"key", IsRequired = true)]
        public string Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
        public string Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserAttributesUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UserAttributesUpdate()
        {
            Pairs = new global::System.Collections.Generic.List<KeyValuePair>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"pairs")]
        public global::System.Collections.Generic.List<KeyValuePair> Pairs { get; private set; }

    }

}

#pragma warning restore 0612, 1591, 3021
