// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: extension_kind.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.extendedmetadata.proto
{

    [global::ProtoBuf.ProtoContract()]
    public enum ExtensionKind
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_EXTENSION")]
        UnknownExtension = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CANVAZ")]
        Canvaz = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"STORYLINES")]
        Storylines = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PODCAST_TOPICS")]
        PodcastTopics = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PODCAST_SEGMENTS")]
        PodcastSegments = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_FILES")]
        AudioFiles = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"TRACK_DESCRIPTOR")]
        TrackDescriptor = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"ARTIST_V4")]
        ArtistV4 = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"ALBUM_V4")]
        AlbumV4 = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"TRACK_V4")]
        TrackV4 = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"SHOW_V4")]
        ShowV4 = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"EPISODE_V4")]
        EpisodeV4 = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"PODCAST_HTML_DESCRIPTION")]
        PodcastHtmlDescription = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"PODCAST_QUOTES")]
        PodcastQuotes = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"USER_PROFILE")]
        UserProfile = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"CANVAS_V1")]
        CanvasV1 = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"SHOW_V4_BASE")]
        ShowV4Base = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"SHOW_V4_EPISODES_ASSOC")]
        ShowV4EpisodesAssoc = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"TRACK_DESCRIPTOR_SIGNATURES")]
        TrackDescriptorSignatures = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"PODCAST_AD_SEGMENTS")]
        PodcastAdSegments = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"TRANSCRIPTS")]
        Transcripts = 21,
    }

}

#pragma warning restore 0612, 1591, 3021
