// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: google.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class Any : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"type_url")]
    [global::System.ComponentModel.DefaultValue("")]
    public string TypeUrl
    {
        get { return __pbn__TypeUrl ?? ""; }
        set { __pbn__TypeUrl = value; }
    }
    public bool ShouldSerializeTypeUrl() => __pbn__TypeUrl != null;
    public void ResetTypeUrl() => __pbn__TypeUrl = null;
    private string __pbn__TypeUrl;

    [global::ProtoBuf.ProtoMember(2, Name = @"value")]
    public byte[] Value
    {
        get { return __pbn__Value; }
        set { __pbn__Value = value; }
    }
    public bool ShouldSerializeValue() => __pbn__Value != null;
    public void ResetValue() => __pbn__Value = null;
    private byte[] __pbn__Value;

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
