// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: keyexchange.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Spotify
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientHello : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"build_info", IsRequired = true)]
        public BuildInfo BuildInfo { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"fingerprints_supported")]
        public global::System.Collections.Generic.List<Fingerprint> FingerprintsSupporteds { get; } = new global::System.Collections.Generic.List<Fingerprint>();

        [global::ProtoBuf.ProtoMember(30, Name = @"cryptosuites_supported")]
        public global::System.Collections.Generic.List<Cryptosuite> CryptosuitesSupporteds { get; } = new global::System.Collections.Generic.List<Cryptosuite>();

        [global::ProtoBuf.ProtoMember(40, Name = @"powschemes_supported")]
        public global::System.Collections.Generic.List<Powscheme> PowschemesSupporteds { get; } = new global::System.Collections.Generic.List<Powscheme>();

        [global::ProtoBuf.ProtoMember(50, Name = @"login_crypto_hello", IsRequired = true)]
        public LoginCryptoHelloUnion LoginCryptoHello { get; set; }

        [global::ProtoBuf.ProtoMember(60, Name = @"client_nonce", IsRequired = true)]
        public byte[] ClientNonce { get; set; }

        [global::ProtoBuf.ProtoMember(70, Name = @"padding")]
        public byte[] Padding
        {
            get { return __pbn__Padding; }
            set { __pbn__Padding = value; }
        }
        public bool ShouldSerializePadding() => __pbn__Padding != null;
        public void ResetPadding() => __pbn__Padding = null;
        private byte[] __pbn__Padding;

        [global::ProtoBuf.ProtoMember(80, Name = @"feature_set")]
        public FeatureSet FeatureSet { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuildInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"product", IsRequired = true)]
        public Product Product { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"product_flags")]
        public global::System.Collections.Generic.List<ProductFlags> ProductFlags { get; } = new global::System.Collections.Generic.List<ProductFlags>();

        [global::ProtoBuf.ProtoMember(30, Name = @"platform", IsRequired = true)]
        public Platform Platform { get; set; }

        [global::ProtoBuf.ProtoMember(40, Name = @"version", IsRequired = true)]
        public ulong Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginCryptoHelloUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"diffie_hellman")]
        public LoginCryptoDiffieHellmanHello DiffieHellman { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginCryptoDiffieHellmanHello : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"gc", IsRequired = true)]
        public byte[] Gc { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"server_keys_known", IsRequired = true)]
        public uint ServerKeysKnown { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FeatureSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"autoupdate2")]
        public bool Autoupdate2
        {
            get { return __pbn__Autoupdate2.GetValueOrDefault(); }
            set { __pbn__Autoupdate2 = value; }
        }
        public bool ShouldSerializeAutoupdate2() => __pbn__Autoupdate2 != null;
        public void ResetAutoupdate2() => __pbn__Autoupdate2 = null;
        private bool? __pbn__Autoupdate2;

        [global::ProtoBuf.ProtoMember(2, Name = @"current_location")]
        public bool CurrentLocation
        {
            get { return __pbn__CurrentLocation.GetValueOrDefault(); }
            set { __pbn__CurrentLocation = value; }
        }
        public bool ShouldSerializeCurrentLocation() => __pbn__CurrentLocation != null;
        public void ResetCurrentLocation() => __pbn__CurrentLocation = null;
        private bool? __pbn__CurrentLocation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class APResponseMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"challenge")]
        public APChallenge Challenge { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"upgrade")]
        public UpgradeRequiredMessage Upgrade { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"login_failed")]
        public APLoginFailed LoginFailed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class APChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"login_crypto_challenge", IsRequired = true)]
        public LoginCryptoChallengeUnion LoginCryptoChallenge { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"fingerprint_challenge", IsRequired = true)]
        public FingerprintChallengeUnion FingerprintChallenge { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"pow_challenge", IsRequired = true)]
        public PoWChallengeUnion PowChallenge { get; set; }

        [global::ProtoBuf.ProtoMember(40, Name = @"crypto_challenge", IsRequired = true)]
        public CryptoChallengeUnion CryptoChallenge { get; set; }

        [global::ProtoBuf.ProtoMember(50, Name = @"server_nonce", IsRequired = true)]
        public byte[] ServerNonce { get; set; }

        [global::ProtoBuf.ProtoMember(60, Name = @"padding")]
        public byte[] Padding
        {
            get { return __pbn__Padding; }
            set { __pbn__Padding = value; }
        }
        public bool ShouldSerializePadding() => __pbn__Padding != null;
        public void ResetPadding() => __pbn__Padding = null;
        private byte[] __pbn__Padding;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginCryptoChallengeUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"diffie_hellman")]
        public LoginCryptoDiffieHellmanChallenge DiffieHellman { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginCryptoDiffieHellmanChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"gs", IsRequired = true)]
        public byte[] Gs { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"server_signature_key", IsRequired = true)]
        public int ServerSignatureKey { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"gs_signature", IsRequired = true)]
        public byte[] GsSignature { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FingerprintChallengeUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"grain")]
        public FingerprintGrainChallenge Grain { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"hmac_ripemd")]
        public FingerprintHmacRipemdChallenge HmacRipemd { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FingerprintGrainChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"kek", IsRequired = true)]
        public byte[] Kek { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FingerprintHmacRipemdChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"challenge", IsRequired = true)]
        public byte[] Challenge { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PoWChallengeUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"hash_cash")]
        public PoWHashCashChallenge HashCash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PoWHashCashChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"prefix")]
        public byte[] Prefix
        {
            get { return __pbn__Prefix; }
            set { __pbn__Prefix = value; }
        }
        public bool ShouldSerializePrefix() => __pbn__Prefix != null;
        public void ResetPrefix() => __pbn__Prefix = null;
        private byte[] __pbn__Prefix;

        [global::ProtoBuf.ProtoMember(20, Name = @"length")]
        public int Length
        {
            get { return __pbn__Length.GetValueOrDefault(); }
            set { __pbn__Length = value; }
        }
        public bool ShouldSerializeLength() => __pbn__Length != null;
        public void ResetLength() => __pbn__Length = null;
        private int? __pbn__Length;

        [global::ProtoBuf.ProtoMember(30, Name = @"target")]
        public int Target
        {
            get { return __pbn__Target.GetValueOrDefault(); }
            set { __pbn__Target = value; }
        }
        public bool ShouldSerializeTarget() => __pbn__Target != null;
        public void ResetTarget() => __pbn__Target = null;
        private int? __pbn__Target;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CryptoChallengeUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"shannon")]
        public CryptoShannonChallenge Shannon { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"rc4_sha1_hmac")]
        public CryptoRc4Sha1HmacChallenge Rc4Sha1Hmac { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CryptoShannonChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CryptoRc4Sha1HmacChallenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpgradeRequiredMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"upgrade_signed_part", IsRequired = true)]
        public byte[] UpgradeSignedPart { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"signature", IsRequired = true)]
        public byte[] Signature { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"http_suffix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string HttpSuffix
        {
            get { return __pbn__HttpSuffix ?? ""; }
            set { __pbn__HttpSuffix = value; }
        }
        public bool ShouldSerializeHttpSuffix() => __pbn__HttpSuffix != null;
        public void ResetHttpSuffix() => __pbn__HttpSuffix = null;
        private string __pbn__HttpSuffix;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class APLoginFailed : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"error_code", IsRequired = true)]
        public ErrorCode ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"retry_delay")]
        public int RetryDelay
        {
            get { return __pbn__RetryDelay.GetValueOrDefault(); }
            set { __pbn__RetryDelay = value; }
        }
        public bool ShouldSerializeRetryDelay() => __pbn__RetryDelay != null;
        public void ResetRetryDelay() => __pbn__RetryDelay = null;
        private int? __pbn__RetryDelay;

        [global::ProtoBuf.ProtoMember(30, Name = @"expiry")]
        public int Expiry
        {
            get { return __pbn__Expiry.GetValueOrDefault(); }
            set { __pbn__Expiry = value; }
        }
        public bool ShouldSerializeExpiry() => __pbn__Expiry != null;
        public void ResetExpiry() => __pbn__Expiry = null;
        private int? __pbn__Expiry;

        [global::ProtoBuf.ProtoMember(40, Name = @"error_description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorDescription
        {
            get { return __pbn__ErrorDescription ?? ""; }
            set { __pbn__ErrorDescription = value; }
        }
        public bool ShouldSerializeErrorDescription() => __pbn__ErrorDescription != null;
        public void ResetErrorDescription() => __pbn__ErrorDescription = null;
        private string __pbn__ErrorDescription;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientResponsePlaintext : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"login_crypto_response", IsRequired = true)]
        public LoginCryptoResponseUnion LoginCryptoResponse { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"pow_response", IsRequired = true)]
        public PoWResponseUnion PowResponse { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"crypto_response", IsRequired = true)]
        public CryptoResponseUnion CryptoResponse { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginCryptoResponseUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"diffie_hellman")]
        public LoginCryptoDiffieHellmanResponse DiffieHellman { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginCryptoDiffieHellmanResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"hmac", IsRequired = true)]
        public byte[] Hmac { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PoWResponseUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"hash_cash")]
        public PoWHashCashResponse HashCash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PoWHashCashResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"hash_suffix", IsRequired = true)]
        public byte[] HashSuffix { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CryptoResponseUnion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10, Name = @"shannon")]
        public CryptoShannonResponse Shannon { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"rc4_sha1_hmac")]
        public CryptoRc4Sha1HmacResponse Rc4Sha1Hmac { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CryptoShannonResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dummy")]
        public int Dummy
        {
            get { return __pbn__Dummy.GetValueOrDefault(); }
            set { __pbn__Dummy = value; }
        }
        public bool ShouldSerializeDummy() => __pbn__Dummy != null;
        public void ResetDummy() => __pbn__Dummy = null;
        private int? __pbn__Dummy;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CryptoRc4Sha1HmacResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dummy")]
        public int Dummy
        {
            get { return __pbn__Dummy.GetValueOrDefault(); }
            set { __pbn__Dummy = value; }
        }
        public bool ShouldSerializeDummy() => __pbn__Dummy != null;
        public void ResetDummy() => __pbn__Dummy = null;
        private int? __pbn__Dummy;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Product
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PRODUCT_CLIENT")]
        ProductClient = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PRODUCT_LIBSPOTIFY")]
        ProductLibspotify = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PRODUCT_MOBILE")]
        ProductMobile = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PRODUCT_PARTNER")]
        ProductPartner = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PRODUCT_LIBSPOTIFY_EMBEDDED")]
        ProductLibspotifyEmbedded = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ProductFlags
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PRODUCT_FLAG_NONE")]
        ProductFlagNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PRODUCT_FLAG_DEV_BUILD")]
        ProductFlagDevBuild = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Platform
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WIN32_X86")]
        PlatformWin32X86 = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_OSX_X86")]
        PlatformOsxX86 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_LINUX_X86")]
        PlatformLinuxX86 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_IPHONE_ARM")]
        PlatformIphoneArm = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_S60_ARM")]
        PlatformS60Arm = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_OSX_PPC")]
        PlatformOsxPpc = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_ANDROID_ARM")]
        PlatformAndroidArm = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WINDOWS_CE_ARM")]
        PlatformWindowsCeArm = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_LINUX_X86_64")]
        PlatformLinuxX8664 = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_OSX_X86_64")]
        PlatformOsxX8664 = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_PALM_ARM")]
        PlatformPalmArm = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_LINUX_SH")]
        PlatformLinuxSh = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_FREEBSD_X86")]
        PlatformFreebsdX86 = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_FREEBSD_X86_64")]
        PlatformFreebsdX8664 = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_BLACKBERRY_ARM")]
        PlatformBlackberryArm = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_SONOS")]
        PlatformSonos = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_LINUX_MIPS")]
        PlatformLinuxMips = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_LINUX_ARM")]
        PlatformLinuxArm = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_LOGITECH_ARM")]
        PlatformLogitechArm = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_LINUX_BLACKFIN")]
        PlatformLinuxBlackfin = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WP7_ARM")]
        PlatformWp7Arm = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_ONKYO_ARM")]
        PlatformOnkyoArm = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_QNXNTO_ARM")]
        PlatformQnxntoArm = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_BCO_ARM")]
        PlatformBcoArm = 23,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Fingerprint
    {
        [global::ProtoBuf.ProtoEnum(Name = @"FINGERPRINT_GRAIN")]
        FingerprintGrain = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FINGERPRINT_HMAC_RIPEMD")]
        FingerprintHmacRipemd = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Cryptosuite
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CRYPTO_SUITE_SHANNON")]
        CryptoSuiteShannon = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CRYPTO_SUITE_RC4_SHA1_HMAC")]
        CryptoSuiteRc4Sha1Hmac = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum Powscheme
    {
        [global::ProtoBuf.ProtoEnum(Name = @"POW_HASH_CASH")]
        PowHashCash = 0,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ErrorCode
    {
        ProtocolError = 0,
        TryAnotherAP = 2,
        BadConnectionId = 5,
        TravelRestriction = 9,
        PremiumAccountRequired = 11,
        BadCredentials = 12,
        CouldNotValidateCredentials = 13,
        AccountExists = 14,
        ExtraVerificationRequired = 15,
        InvalidAppKey = 16,
        ApplicationBanned = 17,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
