// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: mercury.proto

#pragma warning disable 0612, 1591, 3021
namespace Spotify
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MercuryMultiGetRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MercuryMultiGetRequest()
        {
            Requests = new global::System.Collections.Generic.List<MercuryRequest>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"request")]
        public global::System.Collections.Generic.List<MercuryRequest> Requests { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MercuryMultiGetReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MercuryMultiGetReply()
        {
            Replies = new global::System.Collections.Generic.List<MercuryReply>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"reply")]
        public global::System.Collections.Generic.List<MercuryReply> Replies { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MercuryRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MercuryRequest()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri
        {
            get { return __pbn__Uri ?? ""; }
            set { __pbn__Uri = value; }
        }
        public bool ShouldSerializeUri()
        {
            return __pbn__Uri != null;
        }
        public void ResetUri()
        {
            __pbn__Uri = null;
        }
        private string __pbn__Uri;

        [global::ProtoBuf.ProtoMember(2, Name = @"content_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContentType
        {
            get { return __pbn__ContentType ?? ""; }
            set { __pbn__ContentType = value; }
        }
        public bool ShouldSerializeContentType()
        {
            return __pbn__ContentType != null;
        }
        public void ResetContentType()
        {
            __pbn__ContentType = null;
        }
        private string __pbn__ContentType;

        [global::ProtoBuf.ProtoMember(3, Name = @"body")]
        public byte[] Body
        {
            get { return __pbn__Body; }
            set { __pbn__Body = value; }
        }
        public bool ShouldSerializeBody()
        {
            return __pbn__Body != null;
        }
        public void ResetBody()
        {
            __pbn__Body = null;
        }
        private byte[] __pbn__Body;

        [global::ProtoBuf.ProtoMember(4, Name = @"etag")]
        public byte[] Etag
        {
            get { return __pbn__Etag; }
            set { __pbn__Etag = value; }
        }
        public bool ShouldSerializeEtag()
        {
            return __pbn__Etag != null;
        }
        public void ResetEtag()
        {
            __pbn__Etag = null;
        }
        private byte[] __pbn__Etag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MercuryReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MercuryReply()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"status_code", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int StatusCode
        {
            get { return __pbn__StatusCode.GetValueOrDefault(); }
            set { __pbn__StatusCode = value; }
        }
        public bool ShouldSerializeStatusCode()
        {
            return __pbn__StatusCode != null;
        }
        public void ResetStatusCode()
        {
            __pbn__StatusCode = null;
        }
        private int? __pbn__StatusCode;

        [global::ProtoBuf.ProtoMember(2, Name = @"status_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StatusMessage
        {
            get { return __pbn__StatusMessage ?? ""; }
            set { __pbn__StatusMessage = value; }
        }
        public bool ShouldSerializeStatusMessage()
        {
            return __pbn__StatusMessage != null;
        }
        public void ResetStatusMessage()
        {
            __pbn__StatusMessage = null;
        }
        private string __pbn__StatusMessage;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(CachePolicy.CacheNo)]
        public CachePolicy cache_policy
        {
            get { return __pbn__cache_policy ?? CachePolicy.CacheNo; }
            set { __pbn__cache_policy = value; }
        }
        public bool ShouldSerializecache_policy()
        {
            return __pbn__cache_policy != null;
        }
        public void Resetcache_policy()
        {
            __pbn__cache_policy = null;
        }
        private CachePolicy? __pbn__cache_policy;

        [global::ProtoBuf.ProtoMember(4, Name = @"ttl", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Ttl
        {
            get { return __pbn__Ttl.GetValueOrDefault(); }
            set { __pbn__Ttl = value; }
        }
        public bool ShouldSerializeTtl()
        {
            return __pbn__Ttl != null;
        }
        public void ResetTtl()
        {
            __pbn__Ttl = null;
        }
        private int? __pbn__Ttl;

        [global::ProtoBuf.ProtoMember(5, Name = @"etag")]
        public byte[] Etag
        {
            get { return __pbn__Etag; }
            set { __pbn__Etag = value; }
        }
        public bool ShouldSerializeEtag()
        {
            return __pbn__Etag != null;
        }
        public void ResetEtag()
        {
            __pbn__Etag = null;
        }
        private byte[] __pbn__Etag;

        [global::ProtoBuf.ProtoMember(6, Name = @"content_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContentType
        {
            get { return __pbn__ContentType ?? ""; }
            set { __pbn__ContentType = value; }
        }
        public bool ShouldSerializeContentType()
        {
            return __pbn__ContentType != null;
        }
        public void ResetContentType()
        {
            __pbn__ContentType = null;
        }
        private string __pbn__ContentType;

        [global::ProtoBuf.ProtoMember(7, Name = @"body")]
        public byte[] Body
        {
            get { return __pbn__Body; }
            set { __pbn__Body = value; }
        }
        public bool ShouldSerializeBody()
        {
            return __pbn__Body != null;
        }
        public void ResetBody()
        {
            __pbn__Body = null;
        }
        private byte[] __pbn__Body;

        [global::ProtoBuf.ProtoContract()]
        public enum CachePolicy
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CACHE_NO")]
            CacheNo = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CACHE_PRIVATE")]
            CachePrivate = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"CACHE_PUBLIC")]
            CachePublic = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Header : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Header()
        {
            UserFields = new global::System.Collections.Generic.List<UserField>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri
        {
            get { return __pbn__Uri ?? ""; }
            set { __pbn__Uri = value; }
        }
        public bool ShouldSerializeUri()
        {
            return __pbn__Uri != null;
        }
        public void ResetUri()
        {
            __pbn__Uri = null;
        }
        private string __pbn__Uri;

        [global::ProtoBuf.ProtoMember(2, Name = @"content_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContentType
        {
            get { return __pbn__ContentType ?? ""; }
            set { __pbn__ContentType = value; }
        }
        public bool ShouldSerializeContentType()
        {
            return __pbn__ContentType != null;
        }
        public void ResetContentType()
        {
            __pbn__ContentType = null;
        }
        private string __pbn__ContentType;

        [global::ProtoBuf.ProtoMember(3, Name = @"method")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Method
        {
            get { return __pbn__Method ?? ""; }
            set { __pbn__Method = value; }
        }
        public bool ShouldSerializeMethod()
        {
            return __pbn__Method != null;
        }
        public void ResetMethod()
        {
            __pbn__Method = null;
        }
        private string __pbn__Method;

        [global::ProtoBuf.ProtoMember(4, Name = @"status_code", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int StatusCode
        {
            get { return __pbn__StatusCode.GetValueOrDefault(); }
            set { __pbn__StatusCode = value; }
        }
        public bool ShouldSerializeStatusCode()
        {
            return __pbn__StatusCode != null;
        }
        public void ResetStatusCode()
        {
            __pbn__StatusCode = null;
        }
        private int? __pbn__StatusCode;

        [global::ProtoBuf.ProtoMember(6, Name = @"user_fields")]
        public global::System.Collections.Generic.List<UserField> UserFields { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserField : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UserField()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key
        {
            get { return __pbn__Key ?? ""; }
            set { __pbn__Key = value; }
        }
        public bool ShouldSerializeKey()
        {
            return __pbn__Key != null;
        }
        public void ResetKey()
        {
            __pbn__Key = null;
        }
        private string __pbn__Key;

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public byte[] Value
        {
            get { return __pbn__Value; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue()
        {
            return __pbn__Value != null;
        }
        public void ResetValue()
        {
            __pbn__Value = null;
        }
        private byte[] __pbn__Value;

    }

}

#pragma warning restore 0612, 1591, 3021
