// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: metadata.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.metadata.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Artist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gid")]
        public byte[] Gid
        {
            get { return __pbn__Gid; }
            set { __pbn__Gid = value; }
        }
        public bool ShouldSerializeGid() => __pbn__Gid != null;
        public void ResetGid() => __pbn__Gid = null;
        private byte[] __pbn__Gid;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"popularity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Popularity
        {
            get { return __pbn__Popularity.GetValueOrDefault(); }
            set { __pbn__Popularity = value; }
        }
        public bool ShouldSerializePopularity() => __pbn__Popularity != null;
        public void ResetPopularity() => __pbn__Popularity = null;
        private int? __pbn__Popularity;

        [global::ProtoBuf.ProtoMember(4, Name = @"top_track")]
        public global::System.Collections.Generic.List<TopTracks> TopTracks { get; } = new global::System.Collections.Generic.List<TopTracks>();

        [global::ProtoBuf.ProtoMember(5, Name = @"album_group")]
        public global::System.Collections.Generic.List<AlbumGroup> AlbumGroups { get; } = new global::System.Collections.Generic.List<AlbumGroup>();

        [global::ProtoBuf.ProtoMember(6, Name = @"single_group")]
        public global::System.Collections.Generic.List<AlbumGroup> SingleGroups { get; } = new global::System.Collections.Generic.List<AlbumGroup>();

        [global::ProtoBuf.ProtoMember(7, Name = @"compilation_group")]
        public global::System.Collections.Generic.List<AlbumGroup> CompilationGroups { get; } = new global::System.Collections.Generic.List<AlbumGroup>();

        [global::ProtoBuf.ProtoMember(8, Name = @"appears_on_group")]
        public global::System.Collections.Generic.List<AlbumGroup> AppearsOnGroups { get; } = new global::System.Collections.Generic.List<AlbumGroup>();

        [global::ProtoBuf.ProtoMember(9, Name = @"genre")]
        public global::System.Collections.Generic.List<string> Genres { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(10, Name = @"external_id")]
        public global::System.Collections.Generic.List<ExternalId> ExternalIds { get; } = new global::System.Collections.Generic.List<ExternalId>();

        [global::ProtoBuf.ProtoMember(11, Name = @"portrait")]
        public global::System.Collections.Generic.List<Image> Portraits { get; } = new global::System.Collections.Generic.List<Image>();

        [global::ProtoBuf.ProtoMember(12, Name = @"biography")]
        public global::System.Collections.Generic.List<Biography> Biographies { get; } = new global::System.Collections.Generic.List<Biography>();

        [global::ProtoBuf.ProtoMember(13, Name = @"activity_period")]
        public global::System.Collections.Generic.List<ActivityPeriod> ActivityPeriods { get; } = new global::System.Collections.Generic.List<ActivityPeriod>();

        [global::ProtoBuf.ProtoMember(14, Name = @"restriction")]
        public global::System.Collections.Generic.List<Restriction> Restrictions { get; } = new global::System.Collections.Generic.List<Restriction>();

        [global::ProtoBuf.ProtoMember(15, Name = @"related")]
        public global::System.Collections.Generic.List<Artist> Relateds { get; } = new global::System.Collections.Generic.List<Artist>();

        [global::ProtoBuf.ProtoMember(16, Name = @"is_portrait_album_cover")]
        public bool IsPortraitAlbumCover
        {
            get { return __pbn__IsPortraitAlbumCover.GetValueOrDefault(); }
            set { __pbn__IsPortraitAlbumCover = value; }
        }
        public bool ShouldSerializeIsPortraitAlbumCover() => __pbn__IsPortraitAlbumCover != null;
        public void ResetIsPortraitAlbumCover() => __pbn__IsPortraitAlbumCover = null;
        private bool? __pbn__IsPortraitAlbumCover;

        [global::ProtoBuf.ProtoMember(17, Name = @"portrait_group")]
        public ImageGroup PortraitGroup { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"sale_period")]
        public global::System.Collections.Generic.List<SalePeriod> SalePeriods { get; } = new global::System.Collections.Generic.List<SalePeriod>();

        [global::ProtoBuf.ProtoMember(20, Name = @"availability")]
        public global::System.Collections.Generic.List<Availability> Availabilities { get; } = new global::System.Collections.Generic.List<Availability>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Album : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gid")]
        public byte[] Gid
        {
            get { return __pbn__Gid; }
            set { __pbn__Gid = value; }
        }
        public bool ShouldSerializeGid() => __pbn__Gid != null;
        public void ResetGid() => __pbn__Gid = null;
        private byte[] __pbn__Gid;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"artist")]
        public global::System.Collections.Generic.List<Artist> Artists { get; } = new global::System.Collections.Generic.List<Artist>();

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(Type.Album)]
        public Type type
        {
            get { return __pbn__type ?? Type.Album; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(5, Name = @"label")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Label
        {
            get { return __pbn__Label ?? ""; }
            set { __pbn__Label = value; }
        }
        public bool ShouldSerializeLabel() => __pbn__Label != null;
        public void ResetLabel() => __pbn__Label = null;
        private string __pbn__Label;

        [global::ProtoBuf.ProtoMember(6, Name = @"date")]
        public Date Date { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"popularity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Popularity
        {
            get { return __pbn__Popularity.GetValueOrDefault(); }
            set { __pbn__Popularity = value; }
        }
        public bool ShouldSerializePopularity() => __pbn__Popularity != null;
        public void ResetPopularity() => __pbn__Popularity = null;
        private int? __pbn__Popularity;

        [global::ProtoBuf.ProtoMember(8, Name = @"genre")]
        public global::System.Collections.Generic.List<string> Genres { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(9, Name = @"cover")]
        public global::System.Collections.Generic.List<Image> Covers { get; } = new global::System.Collections.Generic.List<Image>();

        [global::ProtoBuf.ProtoMember(10, Name = @"external_id")]
        public global::System.Collections.Generic.List<ExternalId> ExternalIds { get; } = new global::System.Collections.Generic.List<ExternalId>();

        [global::ProtoBuf.ProtoMember(11, Name = @"disc")]
        public global::System.Collections.Generic.List<Disc> Discs { get; } = new global::System.Collections.Generic.List<Disc>();

        [global::ProtoBuf.ProtoMember(12, Name = @"review")]
        public global::System.Collections.Generic.List<string> Reviews { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(13, Name = @"copyright")]
        public global::System.Collections.Generic.List<Copyright> Copyrights { get; } = new global::System.Collections.Generic.List<Copyright>();

        [global::ProtoBuf.ProtoMember(14, Name = @"restriction")]
        public global::System.Collections.Generic.List<Restriction> Restrictions { get; } = new global::System.Collections.Generic.List<Restriction>();

        [global::ProtoBuf.ProtoMember(15, Name = @"related")]
        public global::System.Collections.Generic.List<Album> Relateds { get; } = new global::System.Collections.Generic.List<Album>();

        [global::ProtoBuf.ProtoMember(16, Name = @"sale_period")]
        public global::System.Collections.Generic.List<SalePeriod> SalePeriods { get; } = new global::System.Collections.Generic.List<SalePeriod>();

        [global::ProtoBuf.ProtoMember(17, Name = @"cover_group")]
        public ImageGroup CoverGroup { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"original_title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OriginalTitle
        {
            get { return __pbn__OriginalTitle ?? ""; }
            set { __pbn__OriginalTitle = value; }
        }
        public bool ShouldSerializeOriginalTitle() => __pbn__OriginalTitle != null;
        public void ResetOriginalTitle() => __pbn__OriginalTitle = null;
        private string __pbn__OriginalTitle;

        [global::ProtoBuf.ProtoMember(19, Name = @"version_title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VersionTitle
        {
            get { return __pbn__VersionTitle ?? ""; }
            set { __pbn__VersionTitle = value; }
        }
        public bool ShouldSerializeVersionTitle() => __pbn__VersionTitle != null;
        public void ResetVersionTitle() => __pbn__VersionTitle = null;
        private string __pbn__VersionTitle;

        [global::ProtoBuf.ProtoMember(20, Name = @"type_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TypeStr
        {
            get { return __pbn__TypeStr ?? ""; }
            set { __pbn__TypeStr = value; }
        }
        public bool ShouldSerializeTypeStr() => __pbn__TypeStr != null;
        public void ResetTypeStr() => __pbn__TypeStr = null;
        private string __pbn__TypeStr;

        [global::ProtoBuf.ProtoMember(23, Name = @"availability")]
        public global::System.Collections.Generic.List<Availability> Availabilities { get; } = new global::System.Collections.Generic.List<Availability>();

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ALBUM")]
            Album = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SINGLE")]
            Single = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPILATION")]
            Compilation = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"EP")]
            Ep = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIOBOOK")]
            Audiobook = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"PODCAST")]
            Podcast = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Track : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gid")]
        public byte[] Gid
        {
            get { return __pbn__Gid; }
            set { __pbn__Gid = value; }
        }
        public bool ShouldSerializeGid() => __pbn__Gid != null;
        public void ResetGid() => __pbn__Gid = null;
        private byte[] __pbn__Gid;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"album")]
        public Album Album { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"artist")]
        public global::System.Collections.Generic.List<Artist> Artists { get; } = new global::System.Collections.Generic.List<Artist>();

        [global::ProtoBuf.ProtoMember(5, Name = @"number", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Number
        {
            get { return __pbn__Number.GetValueOrDefault(); }
            set { __pbn__Number = value; }
        }
        public bool ShouldSerializeNumber() => __pbn__Number != null;
        public void ResetNumber() => __pbn__Number = null;
        private int? __pbn__Number;

        [global::ProtoBuf.ProtoMember(6, Name = @"disc_number", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int DiscNumber
        {
            get { return __pbn__DiscNumber.GetValueOrDefault(); }
            set { __pbn__DiscNumber = value; }
        }
        public bool ShouldSerializeDiscNumber() => __pbn__DiscNumber != null;
        public void ResetDiscNumber() => __pbn__DiscNumber = null;
        private int? __pbn__DiscNumber;

        [global::ProtoBuf.ProtoMember(7, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Duration
        {
            get { return __pbn__Duration.GetValueOrDefault(); }
            set { __pbn__Duration = value; }
        }
        public bool ShouldSerializeDuration() => __pbn__Duration != null;
        public void ResetDuration() => __pbn__Duration = null;
        private int? __pbn__Duration;

        [global::ProtoBuf.ProtoMember(8, Name = @"popularity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Popularity
        {
            get { return __pbn__Popularity.GetValueOrDefault(); }
            set { __pbn__Popularity = value; }
        }
        public bool ShouldSerializePopularity() => __pbn__Popularity != null;
        public void ResetPopularity() => __pbn__Popularity = null;
        private int? __pbn__Popularity;

        [global::ProtoBuf.ProtoMember(9, Name = @"explicit")]
        public bool Explicit
        {
            get { return __pbn__Explicit.GetValueOrDefault(); }
            set { __pbn__Explicit = value; }
        }
        public bool ShouldSerializeExplicit() => __pbn__Explicit != null;
        public void ResetExplicit() => __pbn__Explicit = null;
        private bool? __pbn__Explicit;

        [global::ProtoBuf.ProtoMember(10, Name = @"external_id")]
        public global::System.Collections.Generic.List<ExternalId> ExternalIds { get; } = new global::System.Collections.Generic.List<ExternalId>();

        [global::ProtoBuf.ProtoMember(11, Name = @"restriction")]
        public global::System.Collections.Generic.List<Restriction> Restrictions { get; } = new global::System.Collections.Generic.List<Restriction>();

        [global::ProtoBuf.ProtoMember(12, Name = @"file")]
        public global::System.Collections.Generic.List<AudioFile> Files { get; } = new global::System.Collections.Generic.List<AudioFile>();

        [global::ProtoBuf.ProtoMember(13, Name = @"alternative")]
        public global::System.Collections.Generic.List<Track> Alternatives { get; } = new global::System.Collections.Generic.List<Track>();

        [global::ProtoBuf.ProtoMember(14, Name = @"sale_period")]
        public global::System.Collections.Generic.List<SalePeriod> SalePeriods { get; } = new global::System.Collections.Generic.List<SalePeriod>();

        [global::ProtoBuf.ProtoMember(15, Name = @"preview")]
        public global::System.Collections.Generic.List<AudioFile> Previews { get; } = new global::System.Collections.Generic.List<AudioFile>();

        [global::ProtoBuf.ProtoMember(16, Name = @"tags")]
        public global::System.Collections.Generic.List<string> Tags { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(17, Name = @"earliest_live_timestamp")]
        public long EarliestLiveTimestamp
        {
            get { return __pbn__EarliestLiveTimestamp.GetValueOrDefault(); }
            set { __pbn__EarliestLiveTimestamp = value; }
        }
        public bool ShouldSerializeEarliestLiveTimestamp() => __pbn__EarliestLiveTimestamp != null;
        public void ResetEarliestLiveTimestamp() => __pbn__EarliestLiveTimestamp = null;
        private long? __pbn__EarliestLiveTimestamp;

        [global::ProtoBuf.ProtoMember(18, Name = @"has_lyrics")]
        public bool HasLyrics
        {
            get { return __pbn__HasLyrics.GetValueOrDefault(); }
            set { __pbn__HasLyrics = value; }
        }
        public bool ShouldSerializeHasLyrics() => __pbn__HasLyrics != null;
        public void ResetHasLyrics() => __pbn__HasLyrics = null;
        private bool? __pbn__HasLyrics;

        [global::ProtoBuf.ProtoMember(19, Name = @"availability")]
        public global::System.Collections.Generic.List<Availability> Availabilities { get; } = new global::System.Collections.Generic.List<Availability>();

        [global::ProtoBuf.ProtoMember(21, Name = @"licensor")]
        public Licensor Licensor { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Show : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gid")]
        public byte[] Gid
        {
            get { return __pbn__Gid; }
            set { __pbn__Gid = value; }
        }
        public bool ShouldSerializeGid() => __pbn__Gid != null;
        public void ResetGid() => __pbn__Gid = null;
        private byte[] __pbn__Gid;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(64, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return __pbn__Description ?? ""; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription() => __pbn__Description != null;
        public void ResetDescription() => __pbn__Description = null;
        private string __pbn__Description;

        [global::ProtoBuf.ProtoMember(65, Name = @"deprecated_popularity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        [global::System.Obsolete]
        public int DeprecatedPopularity
        {
            get { return __pbn__DeprecatedPopularity.GetValueOrDefault(); }
            set { __pbn__DeprecatedPopularity = value; }
        }
        public bool ShouldSerializeDeprecatedPopularity() => __pbn__DeprecatedPopularity != null;
        public void ResetDeprecatedPopularity() => __pbn__DeprecatedPopularity = null;
        private int? __pbn__DeprecatedPopularity;

        [global::ProtoBuf.ProtoMember(66, Name = @"publisher")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Publisher
        {
            get { return __pbn__Publisher ?? ""; }
            set { __pbn__Publisher = value; }
        }
        public bool ShouldSerializePublisher() => __pbn__Publisher != null;
        public void ResetPublisher() => __pbn__Publisher = null;
        private string __pbn__Publisher;

        [global::ProtoBuf.ProtoMember(67, Name = @"language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Language
        {
            get { return __pbn__Language ?? ""; }
            set { __pbn__Language = value; }
        }
        public bool ShouldSerializeLanguage() => __pbn__Language != null;
        public void ResetLanguage() => __pbn__Language = null;
        private string __pbn__Language;

        [global::ProtoBuf.ProtoMember(68, Name = @"explicit")]
        public bool Explicit
        {
            get { return __pbn__Explicit.GetValueOrDefault(); }
            set { __pbn__Explicit = value; }
        }
        public bool ShouldSerializeExplicit() => __pbn__Explicit != null;
        public void ResetExplicit() => __pbn__Explicit = null;
        private bool? __pbn__Explicit;

        [global::ProtoBuf.ProtoMember(69, Name = @"cover_image")]
        public ImageGroup CoverImage { get; set; }

        [global::ProtoBuf.ProtoMember(70, Name = @"episode")]
        public global::System.Collections.Generic.List<Episode> Episodes { get; } = new global::System.Collections.Generic.List<Episode>();

        [global::ProtoBuf.ProtoMember(71, Name = @"copyright")]
        public global::System.Collections.Generic.List<Copyright> Copyrights { get; } = new global::System.Collections.Generic.List<Copyright>();

        [global::ProtoBuf.ProtoMember(72, Name = @"restriction")]
        public global::System.Collections.Generic.List<Restriction> Restrictions { get; } = new global::System.Collections.Generic.List<Restriction>();

        [global::ProtoBuf.ProtoMember(73, Name = @"keyword")]
        public global::System.Collections.Generic.List<string> Keywords { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(74)]
        [global::System.ComponentModel.DefaultValue(MediaType.Mixed)]
        public MediaType media_type
        {
            get { return __pbn__media_type ?? MediaType.Mixed; }
            set { __pbn__media_type = value; }
        }
        public bool ShouldSerializemedia_type() => __pbn__media_type != null;
        public void Resetmedia_type() => __pbn__media_type = null;
        private MediaType? __pbn__media_type;

        [global::ProtoBuf.ProtoMember(75)]
        [global::System.ComponentModel.DefaultValue(ConsumptionOrder.Sequential)]
        public ConsumptionOrder consumption_order
        {
            get { return __pbn__consumption_order ?? ConsumptionOrder.Sequential; }
            set { __pbn__consumption_order = value; }
        }
        public bool ShouldSerializeconsumption_order() => __pbn__consumption_order != null;
        public void Resetconsumption_order() => __pbn__consumption_order = null;
        private ConsumptionOrder? __pbn__consumption_order;

        [global::ProtoBuf.ProtoMember(78, Name = @"availability")]
        public global::System.Collections.Generic.List<Availability> Availabilities { get; } = new global::System.Collections.Generic.List<Availability>();

        [global::ProtoBuf.ProtoMember(83, Name = @"trailer_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TrailerUri
        {
            get { return __pbn__TrailerUri ?? ""; }
            set { __pbn__TrailerUri = value; }
        }
        public bool ShouldSerializeTrailerUri() => __pbn__TrailerUri != null;
        public void ResetTrailerUri() => __pbn__TrailerUri = null;
        private string __pbn__TrailerUri;

        [global::ProtoBuf.ProtoContract()]
        public enum MediaType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MIXED")]
            Mixed = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO")]
            Audio = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"VIDEO")]
            Video = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum ConsumptionOrder
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SEQUENTIAL")]
            Sequential = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"EPISODIC")]
            Episodic = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"RECENT")]
            Recent = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Episode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gid")]
        public byte[] Gid
        {
            get { return __pbn__Gid; }
            set { __pbn__Gid = value; }
        }
        public bool ShouldSerializeGid() => __pbn__Gid != null;
        public void ResetGid() => __pbn__Gid = null;
        private byte[] __pbn__Gid;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(7, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Duration
        {
            get { return __pbn__Duration.GetValueOrDefault(); }
            set { __pbn__Duration = value; }
        }
        public bool ShouldSerializeDuration() => __pbn__Duration != null;
        public void ResetDuration() => __pbn__Duration = null;
        private int? __pbn__Duration;

        [global::ProtoBuf.ProtoMember(12, Name = @"audio")]
        public global::System.Collections.Generic.List<AudioFile> Audioes { get; } = new global::System.Collections.Generic.List<AudioFile>();

        [global::ProtoBuf.ProtoMember(64, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return __pbn__Description ?? ""; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription() => __pbn__Description != null;
        public void ResetDescription() => __pbn__Description = null;
        private string __pbn__Description;

        [global::ProtoBuf.ProtoMember(65, Name = @"number", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Number
        {
            get { return __pbn__Number.GetValueOrDefault(); }
            set { __pbn__Number = value; }
        }
        public bool ShouldSerializeNumber() => __pbn__Number != null;
        public void ResetNumber() => __pbn__Number = null;
        private int? __pbn__Number;

        [global::ProtoBuf.ProtoMember(66, Name = @"publish_time")]
        public Date PublishTime { get; set; }

        [global::ProtoBuf.ProtoMember(67, Name = @"deprecated_popularity", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        [global::System.Obsolete]
        public int DeprecatedPopularity
        {
            get { return __pbn__DeprecatedPopularity.GetValueOrDefault(); }
            set { __pbn__DeprecatedPopularity = value; }
        }
        public bool ShouldSerializeDeprecatedPopularity() => __pbn__DeprecatedPopularity != null;
        public void ResetDeprecatedPopularity() => __pbn__DeprecatedPopularity = null;
        private int? __pbn__DeprecatedPopularity;

        [global::ProtoBuf.ProtoMember(68, Name = @"cover_image")]
        public ImageGroup CoverImage { get; set; }

        [global::ProtoBuf.ProtoMember(69, Name = @"language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Language
        {
            get { return __pbn__Language ?? ""; }
            set { __pbn__Language = value; }
        }
        public bool ShouldSerializeLanguage() => __pbn__Language != null;
        public void ResetLanguage() => __pbn__Language = null;
        private string __pbn__Language;

        [global::ProtoBuf.ProtoMember(70, Name = @"explicit")]
        public bool Explicit
        {
            get { return __pbn__Explicit.GetValueOrDefault(); }
            set { __pbn__Explicit = value; }
        }
        public bool ShouldSerializeExplicit() => __pbn__Explicit != null;
        public void ResetExplicit() => __pbn__Explicit = null;
        private bool? __pbn__Explicit;

        [global::ProtoBuf.ProtoMember(71, Name = @"show")]
        public Show Show { get; set; }

        [global::ProtoBuf.ProtoMember(72, Name = @"video")]
        public global::System.Collections.Generic.List<VideoFile> Videoes { get; } = new global::System.Collections.Generic.List<VideoFile>();

        [global::ProtoBuf.ProtoMember(73, Name = @"video_preview")]
        public global::System.Collections.Generic.List<VideoFile> VideoPreviews { get; } = new global::System.Collections.Generic.List<VideoFile>();

        [global::ProtoBuf.ProtoMember(74, Name = @"audio_preview")]
        public global::System.Collections.Generic.List<AudioFile> AudioPreviews { get; } = new global::System.Collections.Generic.List<AudioFile>();

        [global::ProtoBuf.ProtoMember(75, Name = @"restriction")]
        public global::System.Collections.Generic.List<Restriction> Restrictions { get; } = new global::System.Collections.Generic.List<Restriction>();

        [global::ProtoBuf.ProtoMember(76, Name = @"freeze_frame")]
        public ImageGroup FreezeFrame { get; set; }

        [global::ProtoBuf.ProtoMember(77, Name = @"keyword")]
        public global::System.Collections.Generic.List<string> Keywords { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(81, Name = @"allow_background_playback")]
        public bool AllowBackgroundPlayback
        {
            get { return __pbn__AllowBackgroundPlayback.GetValueOrDefault(); }
            set { __pbn__AllowBackgroundPlayback = value; }
        }
        public bool ShouldSerializeAllowBackgroundPlayback() => __pbn__AllowBackgroundPlayback != null;
        public void ResetAllowBackgroundPlayback() => __pbn__AllowBackgroundPlayback = null;
        private bool? __pbn__AllowBackgroundPlayback;

        [global::ProtoBuf.ProtoMember(82, Name = @"availability")]
        public global::System.Collections.Generic.List<Availability> Availabilities { get; } = new global::System.Collections.Generic.List<Availability>();

        [global::ProtoBuf.ProtoMember(83, Name = @"external_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ExternalUrl
        {
            get { return __pbn__ExternalUrl ?? ""; }
            set { __pbn__ExternalUrl = value; }
        }
        public bool ShouldSerializeExternalUrl() => __pbn__ExternalUrl != null;
        public void ResetExternalUrl() => __pbn__ExternalUrl = null;
        private string __pbn__ExternalUrl;

        [global::ProtoBuf.ProtoMember(87, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(EpisodeType.Full)]
        public EpisodeType Type
        {
            get { return __pbn__Type ?? EpisodeType.Full; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private EpisodeType? __pbn__Type;

        [global::ProtoBuf.ProtoContract()]
        public enum EpisodeType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"FULL")]
            Full = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TRAILER")]
            Trailer = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BONUS")]
            Bonus = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Licensor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public byte[] Uuid
        {
            get { return __pbn__Uuid; }
            set { __pbn__Uuid = value; }
        }
        public bool ShouldSerializeUuid() => __pbn__Uuid != null;
        public void ResetUuid() => __pbn__Uuid = null;
        private byte[] __pbn__Uuid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TopTracks : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"country")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Country
        {
            get { return __pbn__Country ?? ""; }
            set { __pbn__Country = value; }
        }
        public bool ShouldSerializeCountry() => __pbn__Country != null;
        public void ResetCountry() => __pbn__Country = null;
        private string __pbn__Country;

        [global::ProtoBuf.ProtoMember(2, Name = @"track")]
        public global::System.Collections.Generic.List<Track> Tracks { get; } = new global::System.Collections.Generic.List<Track>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActivityPeriod : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_year", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int StartYear
        {
            get { return __pbn__StartYear.GetValueOrDefault(); }
            set { __pbn__StartYear = value; }
        }
        public bool ShouldSerializeStartYear() => __pbn__StartYear != null;
        public void ResetStartYear() => __pbn__StartYear = null;
        private int? __pbn__StartYear;

        [global::ProtoBuf.ProtoMember(2, Name = @"end_year", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int EndYear
        {
            get { return __pbn__EndYear.GetValueOrDefault(); }
            set { __pbn__EndYear = value; }
        }
        public bool ShouldSerializeEndYear() => __pbn__EndYear != null;
        public void ResetEndYear() => __pbn__EndYear = null;
        private int? __pbn__EndYear;

        [global::ProtoBuf.ProtoMember(3, Name = @"decade", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Decade
        {
            get { return __pbn__Decade.GetValueOrDefault(); }
            set { __pbn__Decade = value; }
        }
        public bool ShouldSerializeDecade() => __pbn__Decade != null;
        public void ResetDecade() => __pbn__Decade = null;
        private int? __pbn__Decade;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AlbumGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"album")]
        public global::System.Collections.Generic.List<Album> Albums { get; } = new global::System.Collections.Generic.List<Album>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Date : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"year", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Year
        {
            get { return __pbn__Year.GetValueOrDefault(); }
            set { __pbn__Year = value; }
        }
        public bool ShouldSerializeYear() => __pbn__Year != null;
        public void ResetYear() => __pbn__Year = null;
        private int? __pbn__Year;

        [global::ProtoBuf.ProtoMember(2, Name = @"month", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Month
        {
            get { return __pbn__Month.GetValueOrDefault(); }
            set { __pbn__Month = value; }
        }
        public bool ShouldSerializeMonth() => __pbn__Month != null;
        public void ResetMonth() => __pbn__Month = null;
        private int? __pbn__Month;

        [global::ProtoBuf.ProtoMember(3, Name = @"day", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Day
        {
            get { return __pbn__Day.GetValueOrDefault(); }
            set { __pbn__Day = value; }
        }
        public bool ShouldSerializeDay() => __pbn__Day != null;
        public void ResetDay() => __pbn__Day = null;
        private int? __pbn__Day;

        [global::ProtoBuf.ProtoMember(4, Name = @"hour", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Hour
        {
            get { return __pbn__Hour.GetValueOrDefault(); }
            set { __pbn__Hour = value; }
        }
        public bool ShouldSerializeHour() => __pbn__Hour != null;
        public void ResetHour() => __pbn__Hour = null;
        private int? __pbn__Hour;

        [global::ProtoBuf.ProtoMember(5, Name = @"minute", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Minute
        {
            get { return __pbn__Minute.GetValueOrDefault(); }
            set { __pbn__Minute = value; }
        }
        public bool ShouldSerializeMinute() => __pbn__Minute != null;
        public void ResetMinute() => __pbn__Minute = null;
        private int? __pbn__Minute;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Image : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"file_id")]
        public byte[] FileId
        {
            get { return __pbn__FileId; }
            set { __pbn__FileId = value; }
        }
        public bool ShouldSerializeFileId() => __pbn__FileId != null;
        public void ResetFileId() => __pbn__FileId = null;
        private byte[] __pbn__FileId;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(Size.Default)]
        public Size size
        {
            get { return __pbn__size ?? Size.Default; }
            set { __pbn__size = value; }
        }
        public bool ShouldSerializesize() => __pbn__size != null;
        public void Resetsize() => __pbn__size = null;
        private Size? __pbn__size;

        [global::ProtoBuf.ProtoMember(3, Name = @"width", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Width
        {
            get { return __pbn__Width.GetValueOrDefault(); }
            set { __pbn__Width = value; }
        }
        public bool ShouldSerializeWidth() => __pbn__Width != null;
        public void ResetWidth() => __pbn__Width = null;
        private int? __pbn__Width;

        [global::ProtoBuf.ProtoMember(4, Name = @"height", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Height
        {
            get { return __pbn__Height.GetValueOrDefault(); }
            set { __pbn__Height = value; }
        }
        public bool ShouldSerializeHeight() => __pbn__Height != null;
        public void ResetHeight() => __pbn__Height = null;
        private int? __pbn__Height;

        [global::ProtoBuf.ProtoContract()]
        public enum Size
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DEFAULT")]
            Default = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SMALL")]
            Small = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"LARGE")]
            Large = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"XLARGE")]
            Xlarge = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ImageGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"image")]
        public global::System.Collections.Generic.List<Image> Images { get; } = new global::System.Collections.Generic.List<Image>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Biography : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text
        {
            get { return __pbn__Text ?? ""; }
            set { __pbn__Text = value; }
        }
        public bool ShouldSerializeText() => __pbn__Text != null;
        public void ResetText() => __pbn__Text = null;
        private string __pbn__Text;

        [global::ProtoBuf.ProtoMember(2, Name = @"portrait")]
        public global::System.Collections.Generic.List<Image> Portraits { get; } = new global::System.Collections.Generic.List<Image>();

        [global::ProtoBuf.ProtoMember(3, Name = @"portrait_group")]
        public global::System.Collections.Generic.List<ImageGroup> PortraitGroups { get; } = new global::System.Collections.Generic.List<ImageGroup>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Disc : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"number", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Number
        {
            get { return __pbn__Number.GetValueOrDefault(); }
            set { __pbn__Number = value; }
        }
        public bool ShouldSerializeNumber() => __pbn__Number != null;
        public void ResetNumber() => __pbn__Number = null;
        private int? __pbn__Number;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"track")]
        public global::System.Collections.Generic.List<Track> Tracks { get; } = new global::System.Collections.Generic.List<Track>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Copyright : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(Type.P)]
        public Type type
        {
            get { return __pbn__type ?? Type.P; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(2, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text
        {
            get { return __pbn__Text ?? ""; }
            set { __pbn__Text = value; }
        }
        public bool ShouldSerializeText() => __pbn__Text != null;
        public void ResetText() => __pbn__Text = null;
        private string __pbn__Text;

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            P = 0,
            C = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Restriction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"catalogue")]
        public global::System.Collections.Generic.List<Catalogue> Catalogues { get; } = new global::System.Collections.Generic.List<Catalogue>();

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(Type.Streaming)]
        public Type type
        {
            get { return __pbn__type ?? Type.Streaming; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(5, Name = @"catalogue_str")]
        public global::System.Collections.Generic.List<string> CatalogueStrs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"countries_allowed")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CountriesAllowed
        {
            get { return __pbn__country_restriction.Is(2) ? ((string)__pbn__country_restriction.Object) : ""; }
            set { __pbn__country_restriction = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeCountriesAllowed() => __pbn__country_restriction.Is(2);
        public void ResetCountriesAllowed() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__country_restriction, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__country_restriction;

        [global::ProtoBuf.ProtoMember(3, Name = @"countries_forbidden")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CountriesForbidden
        {
            get { return __pbn__country_restriction.Is(3) ? ((string)__pbn__country_restriction.Object) : ""; }
            set { __pbn__country_restriction = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeCountriesForbidden() => __pbn__country_restriction.Is(3);
        public void ResetCountriesForbidden() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__country_restriction, 3);

        [global::ProtoBuf.ProtoContract()]
        public enum Catalogue
        {
            [global::ProtoBuf.ProtoEnum(Name = @"AD")]
            Ad = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIPTION")]
            Subscription = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CATALOGUE_ALL")]
            CatalogueAll = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SHUFFLE")]
            Shuffle = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"COMMERCIAL")]
            Commercial = 4,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"STREAMING")]
            Streaming = 0,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Availability : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"catalogue_str")]
        public global::System.Collections.Generic.List<string> CatalogueStrs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"start")]
        public Date Start { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SalePeriod : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"restriction")]
        public global::System.Collections.Generic.List<Restriction> Restrictions { get; } = new global::System.Collections.Generic.List<Restriction>();

        [global::ProtoBuf.ProtoMember(2, Name = @"start")]
        public Date Start { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"end")]
        public Date End { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExternalId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type
        {
            get { return __pbn__Type ?? ""; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private string __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id
        {
            get { return __pbn__Id ?? ""; }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private string __pbn__Id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AudioFile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"file_id")]
        public byte[] FileId
        {
            get { return __pbn__FileId; }
            set { __pbn__FileId = value; }
        }
        public bool ShouldSerializeFileId() => __pbn__FileId != null;
        public void ResetFileId() => __pbn__FileId = null;
        private byte[] __pbn__FileId;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(Format.OggVorbis96)]
        public Format format
        {
            get { return __pbn__format ?? Format.OggVorbis96; }
            set { __pbn__format = value; }
        }
        public bool ShouldSerializeformat() => __pbn__format != null;
        public void Resetformat() => __pbn__format = null;
        private Format? __pbn__format;

        [global::ProtoBuf.ProtoContract()]
        public enum Format
        {
            [global::ProtoBuf.ProtoEnum(Name = @"OGG_VORBIS_96")]
            OggVorbis96 = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"OGG_VORBIS_160")]
            OggVorbis160 = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"OGG_VORBIS_320")]
            OggVorbis320 = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"MP3_256")]
            Mp3256 = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MP3_320")]
            Mp3320 = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"MP3_160")]
            Mp3160 = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"MP3_96")]
            Mp396 = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"MP3_160_ENC")]
            Mp3160Enc = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"AAC_24")]
            Aac24 = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"AAC_48")]
            Aac48 = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"AAC_24_NORM")]
            Aac24Norm = 16,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VideoFile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"file_id")]
        public byte[] FileId
        {
            get { return __pbn__FileId; }
            set { __pbn__FileId = value; }
        }
        public bool ShouldSerializeFileId() => __pbn__FileId != null;
        public void ResetFileId() => __pbn__FileId = null;
        private byte[] __pbn__FileId;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
