// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: play_origin.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.player.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayOrigin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayOrigin()
        {
            FeatureClasses = new global::System.Collections.Generic.List<string>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"feature_identifier")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeatureIdentifier
        {
            get { return __pbn__FeatureIdentifier ?? ""; }
            set { __pbn__FeatureIdentifier = value; }
        }
        public bool ShouldSerializeFeatureIdentifier()
        {
            return __pbn__FeatureIdentifier != null;
        }
        public void ResetFeatureIdentifier()
        {
            __pbn__FeatureIdentifier = null;
        }
        private string __pbn__FeatureIdentifier;

        [global::ProtoBuf.ProtoMember(2, Name = @"feature_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeatureVersion
        {
            get { return __pbn__FeatureVersion ?? ""; }
            set { __pbn__FeatureVersion = value; }
        }
        public bool ShouldSerializeFeatureVersion()
        {
            return __pbn__FeatureVersion != null;
        }
        public void ResetFeatureVersion()
        {
            __pbn__FeatureVersion = null;
        }
        private string __pbn__FeatureVersion;

        [global::ProtoBuf.ProtoMember(3, Name = @"view_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ViewUri
        {
            get { return __pbn__ViewUri ?? ""; }
            set { __pbn__ViewUri = value; }
        }
        public bool ShouldSerializeViewUri()
        {
            return __pbn__ViewUri != null;
        }
        public void ResetViewUri()
        {
            __pbn__ViewUri = null;
        }
        private string __pbn__ViewUri;

        [global::ProtoBuf.ProtoMember(4, Name = @"external_referrer")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ExternalReferrer
        {
            get { return __pbn__ExternalReferrer ?? ""; }
            set { __pbn__ExternalReferrer = value; }
        }
        public bool ShouldSerializeExternalReferrer()
        {
            return __pbn__ExternalReferrer != null;
        }
        public void ResetExternalReferrer()
        {
            __pbn__ExternalReferrer = null;
        }
        private string __pbn__ExternalReferrer;

        [global::ProtoBuf.ProtoMember(5, Name = @"referrer_identifier")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ReferrerIdentifier
        {
            get { return __pbn__ReferrerIdentifier ?? ""; }
            set { __pbn__ReferrerIdentifier = value; }
        }
        public bool ShouldSerializeReferrerIdentifier()
        {
            return __pbn__ReferrerIdentifier != null;
        }
        public void ResetReferrerIdentifier()
        {
            __pbn__ReferrerIdentifier = null;
        }
        private string __pbn__ReferrerIdentifier;

        [global::ProtoBuf.ProtoMember(6, Name = @"device_identifier")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceIdentifier
        {
            get { return __pbn__DeviceIdentifier ?? ""; }
            set { __pbn__DeviceIdentifier = value; }
        }
        public bool ShouldSerializeDeviceIdentifier()
        {
            return __pbn__DeviceIdentifier != null;
        }
        public void ResetDeviceIdentifier()
        {
            __pbn__DeviceIdentifier = null;
        }
        private string __pbn__DeviceIdentifier;

        [global::ProtoBuf.ProtoMember(7, Name = @"feature_classes")]
        public global::System.Collections.Generic.List<string> FeatureClasses { get; private set; }

    }

}

#pragma warning restore 0612, 1591, 3021
