// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: player.proto

#pragma warning disable 0612, 1591, 3021
namespace Connectstate
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayerState()
        {
            ContextUri = "";
            ContextUrl = "";
            PlaybackId = "";
            PrevTracks = new global::System.Collections.Generic.List<ProvidedTrack>();
            NextTracks = new global::System.Collections.Generic.List<ProvidedTrack>();
            ContextMetadatas = new global::System.Collections.Generic.Dictionary<string, string>();
            PageMetadatas = new global::System.Collections.Generic.Dictionary<string, string>();
            SessionId = "";
            QueueRevision = "";
            EntityUri = "";
            Reverses = new global::System.Collections.Generic.List<ProvidedTrack>();
            Futures = new global::System.Collections.Generic.List<ProvidedTrack>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"context_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContextUri { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"context_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ContextUrl { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"context_restrictions")]
        public Restrictions ContextRestrictions { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"play_origin")]
        public PlayOrigin PlayOrigin { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"index")]
        public ContextIndex Index { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"track")]
        public ProvidedTrack Track { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"playback_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlaybackId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"playback_speed")]
        public double PlaybackSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"position_as_of_timestamp")]
        public long PositionAsOfTimestamp { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"duration")]
        public long Duration { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"is_playing")]
        public bool IsPlaying { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"is_paused")]
        public bool IsPaused { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"is_buffering")]
        public bool IsBuffering { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"is_system_initiated")]
        public bool IsSystemInitiated { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"options")]
        public ContextPlayerOptions Options { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"restrictions")]
        public Restrictions Restrictions { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"suppressions")]
        public Suppressions Suppressions { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"prev_tracks")]
        public global::System.Collections.Generic.List<ProvidedTrack> PrevTracks { get; private set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"next_tracks")]
        public global::System.Collections.Generic.List<ProvidedTrack> NextTracks { get; private set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"context_metadata")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> ContextMetadatas { get; private set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"page_metadata")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> PageMetadatas { get; private set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"queue_revision")]
        [global::System.ComponentModel.DefaultValue("")]
        public string QueueRevision { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"position")]
        public long Position { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"entity_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EntityUri { get; set; }

        [global::ProtoBuf.ProtoMember(27, Name = @"reverse")]
        public global::System.Collections.Generic.List<ProvidedTrack> Reverses { get; private set; }

        [global::ProtoBuf.ProtoMember(28, Name = @"future")]
        public global::System.Collections.Generic.List<ProvidedTrack> Futures { get; private set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"playback_quality")]
        public PlaybackQuality PlaybackQuality { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProvidedTrack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ProvidedTrack()
        {
            Uri = "";
            Uid = "";
            Metadatas = new global::System.Collections.Generic.Dictionary<string, string>();
            Removeds = new global::System.Collections.Generic.List<string>();
            Blockeds = new global::System.Collections.Generic.List<string>();
            Provider = "";
            AlbumUri = "";
            DisallowReasons = new global::System.Collections.Generic.List<string>();
            ArtistUri = "";
            DisallowUndecideds = new global::System.Collections.Generic.List<string>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Metadatas { get; private set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"removed")]
        public global::System.Collections.Generic.List<string> Removeds { get; private set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"blocked")]
        public global::System.Collections.Generic.List<string> Blockeds { get; private set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"provider")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Provider { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"restrictions")]
        public Restrictions Restrictions { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"album_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AlbumUri { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"disallow_reasons")]
        public global::System.Collections.Generic.List<string> DisallowReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"artist_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ArtistUri { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"disallow_undecided")]
        public global::System.Collections.Generic.List<string> DisallowUndecideds { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContextIndex : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ContextIndex()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"page")]
        public uint Page { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"track")]
        public uint Track { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Restrictions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Restrictions()
        {
            DisallowPausingReasons = new global::System.Collections.Generic.List<string>();
            DisallowResumingReasons = new global::System.Collections.Generic.List<string>();
            DisallowSeekingReasons = new global::System.Collections.Generic.List<string>();
            DisallowPeekingPrevReasons = new global::System.Collections.Generic.List<string>();
            DisallowPeekingNextReasons = new global::System.Collections.Generic.List<string>();
            DisallowSkippingPrevReasons = new global::System.Collections.Generic.List<string>();
            DisallowSkippingNextReasons = new global::System.Collections.Generic.List<string>();
            DisallowTogglingRepeatContextReasons = new global::System.Collections.Generic.List<string>();
            DisallowTogglingRepeatTrackReasons = new global::System.Collections.Generic.List<string>();
            DisallowTogglingShuffleReasons = new global::System.Collections.Generic.List<string>();
            DisallowSetQueueReasons = new global::System.Collections.Generic.List<string>();
            DisallowInterruptingPlaybackReasons = new global::System.Collections.Generic.List<string>();
            DisallowTransferringPlaybackReasons = new global::System.Collections.Generic.List<string>();
            DisallowRemoteControlReasons = new global::System.Collections.Generic.List<string>();
            DisallowInsertingIntoNextTracksReasons = new global::System.Collections.Generic.List<string>();
            DisallowInsertingIntoContextTracksReasons = new global::System.Collections.Generic.List<string>();
            DisallowReorderingInNextTracksReasons = new global::System.Collections.Generic.List<string>();
            DisallowReorderingInContextTracksReasons = new global::System.Collections.Generic.List<string>();
            DisallowRemovingFromNextTracksReasons = new global::System.Collections.Generic.List<string>();
            DisallowRemovingFromContextTracksReasons = new global::System.Collections.Generic.List<string>();
            DisallowUpdatingContextReasons = new global::System.Collections.Generic.List<string>();
            DisallowPlayingReasons = new global::System.Collections.Generic.List<string>();
            DisallowStoppingReasons = new global::System.Collections.Generic.List<string>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"disallow_pausing_reasons")]
        public global::System.Collections.Generic.List<string> DisallowPausingReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"disallow_resuming_reasons")]
        public global::System.Collections.Generic.List<string> DisallowResumingReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"disallow_seeking_reasons")]
        public global::System.Collections.Generic.List<string> DisallowSeekingReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"disallow_peeking_prev_reasons")]
        public global::System.Collections.Generic.List<string> DisallowPeekingPrevReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"disallow_peeking_next_reasons")]
        public global::System.Collections.Generic.List<string> DisallowPeekingNextReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"disallow_skipping_prev_reasons")]
        public global::System.Collections.Generic.List<string> DisallowSkippingPrevReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"disallow_skipping_next_reasons")]
        public global::System.Collections.Generic.List<string> DisallowSkippingNextReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"disallow_toggling_repeat_context_reasons")]
        public global::System.Collections.Generic.List<string> DisallowTogglingRepeatContextReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"disallow_toggling_repeat_track_reasons")]
        public global::System.Collections.Generic.List<string> DisallowTogglingRepeatTrackReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"disallow_toggling_shuffle_reasons")]
        public global::System.Collections.Generic.List<string> DisallowTogglingShuffleReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"disallow_set_queue_reasons")]
        public global::System.Collections.Generic.List<string> DisallowSetQueueReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"disallow_interrupting_playback_reasons")]
        public global::System.Collections.Generic.List<string> DisallowInterruptingPlaybackReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"disallow_transferring_playback_reasons")]
        public global::System.Collections.Generic.List<string> DisallowTransferringPlaybackReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"disallow_remote_control_reasons")]
        public global::System.Collections.Generic.List<string> DisallowRemoteControlReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"disallow_inserting_into_next_tracks_reasons")]
        public global::System.Collections.Generic.List<string> DisallowInsertingIntoNextTracksReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"disallow_inserting_into_context_tracks_reasons")]
        public global::System.Collections.Generic.List<string> DisallowInsertingIntoContextTracksReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"disallow_reordering_in_next_tracks_reasons")]
        public global::System.Collections.Generic.List<string> DisallowReorderingInNextTracksReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"disallow_reordering_in_context_tracks_reasons")]
        public global::System.Collections.Generic.List<string> DisallowReorderingInContextTracksReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"disallow_removing_from_next_tracks_reasons")]
        public global::System.Collections.Generic.List<string> DisallowRemovingFromNextTracksReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"disallow_removing_from_context_tracks_reasons")]
        public global::System.Collections.Generic.List<string> DisallowRemovingFromContextTracksReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"disallow_updating_context_reasons")]
        public global::System.Collections.Generic.List<string> DisallowUpdatingContextReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"disallow_playing_reasons")]
        public global::System.Collections.Generic.List<string> DisallowPlayingReasons { get; private set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"disallow_stopping_reasons")]
        public global::System.Collections.Generic.List<string> DisallowStoppingReasons { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayOrigin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayOrigin()
        {
            FeatureIdentifier = "";
            FeatureVersion = "";
            ViewUri = "";
            ExternalReferrer = "";
            ReferrerIdentifier = "";
            DeviceIdentifier = "";
            FeatureClasses = new global::System.Collections.Generic.List<string>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"feature_identifier")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeatureIdentifier { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"feature_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FeatureVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"view_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ViewUri { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"external_referrer")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ExternalReferrer { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"referrer_identifier")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ReferrerIdentifier { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"device_identifier")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceIdentifier { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"feature_classes")]
        public global::System.Collections.Generic.List<string> FeatureClasses { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContextPlayerOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ContextPlayerOptions()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"shuffling_context")]
        public bool ShufflingContext { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"repeating_context")]
        public bool RepeatingContext { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"repeating_track")]
        public bool RepeatingTrack { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Suppressions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Suppressions()
        {
            Providers = new global::System.Collections.Generic.List<string>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"providers")]
        public global::System.Collections.Generic.List<string> Providers { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlaybackQuality : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlaybackQuality()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"bitrate_level")]
        public BitrateLevel BitrateLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"strategy")]
        public BitrateStrategy Strategy { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"target_bitrate_level")]
        public BitrateLevel TargetBitrateLevel { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"target_bitrate_available")]
        public bool TargetBitrateAvailable { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"hifi_status")]
        public HiFiStatus HifiStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum BitrateLevel
    {
        [global::ProtoBuf.ProtoEnum(Name = @"unknown")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"low")]
        Low = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"normal")]
        Normal = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"high")]
        High = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"veryhigh")]
        Veryhigh = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"normalized")]
        Normalized = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BitrateStrategy
    {
        [global::ProtoBuf.ProtoEnum(Name = @"unknown_strategy")]
        UnknownStrategy = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"best_matching")]
        BestMatching = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"backend_advised")]
        BackendAdvised = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"offlined_file")]
        OfflinedFile = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"cached_file")]
        CachedFile = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"local_file")]
        LocalFile = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum HiFiStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"none")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"off")]
        Off = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"on")]
        On = 2,
    }

}

#pragma warning restore 0612, 1591, 3021
