// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: playback.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.player.proto.transfer
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Playback : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Playback()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp")]
        public long Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp()
        {
            return __pbn__Timestamp != null;
        }
        public void ResetTimestamp()
        {
            __pbn__Timestamp = null;
        }
        private long? __pbn__Timestamp;

        [global::ProtoBuf.ProtoMember(2, Name = @"position_as_of_timestamp")]
        public int PositionAsOfTimestamp
        {
            get { return __pbn__PositionAsOfTimestamp.GetValueOrDefault(); }
            set { __pbn__PositionAsOfTimestamp = value; }
        }
        public bool ShouldSerializePositionAsOfTimestamp()
        {
            return __pbn__PositionAsOfTimestamp != null;
        }
        public void ResetPositionAsOfTimestamp()
        {
            __pbn__PositionAsOfTimestamp = null;
        }
        private int? __pbn__PositionAsOfTimestamp;

        [global::ProtoBuf.ProtoMember(3, Name = @"playback_speed")]
        public double PlaybackSpeed
        {
            get { return __pbn__PlaybackSpeed.GetValueOrDefault(); }
            set { __pbn__PlaybackSpeed = value; }
        }
        public bool ShouldSerializePlaybackSpeed()
        {
            return __pbn__PlaybackSpeed != null;
        }
        public void ResetPlaybackSpeed()
        {
            __pbn__PlaybackSpeed = null;
        }
        private double? __pbn__PlaybackSpeed;

        [global::ProtoBuf.ProtoMember(4, Name = @"is_paused")]
        public bool IsPaused
        {
            get { return __pbn__IsPaused.GetValueOrDefault(); }
            set { __pbn__IsPaused = value; }
        }
        public bool ShouldSerializeIsPaused()
        {
            return __pbn__IsPaused != null;
        }
        public void ResetIsPaused()
        {
            __pbn__IsPaused = null;
        }
        private bool? __pbn__IsPaused;

        [global::ProtoBuf.ProtoMember(5, Name = @"current_track")]
        public global::spotify.player.proto.ContextTrack CurrentTrack { get; set; }

    }

}

#pragma warning restore 0612, 1591, 3021
