// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: playlist_annotate3.proto

#pragma warning disable 0612, 1591, 3021
namespace spotifyplaylistannotate3.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TakedownRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TakedownRequest()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"abuse_report_state")]
        [global::System.ComponentModel.DefaultValue(AbuseReportState.Ok)]
        public AbuseReportState AbuseReportState
        {
            get { return __pbn__AbuseReportState ?? AbuseReportState.Ok; }
            set { __pbn__AbuseReportState = value; }
        }
        public bool ShouldSerializeAbuseReportState()
        {
            return __pbn__AbuseReportState != null;
        }
        public void ResetAbuseReportState()
        {
            __pbn__AbuseReportState = null;
        }
        private AbuseReportState? __pbn__AbuseReportState;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AnnotateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public AnnotateRequest()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return __pbn__Description ?? ""; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription()
        {
            return __pbn__Description != null;
        }
        public void ResetDescription()
        {
            __pbn__Description = null;
        }
        private string __pbn__Description;

        [global::ProtoBuf.ProtoMember(2, Name = @"image_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ImageUri
        {
            get { return __pbn__ImageUri ?? ""; }
            set { __pbn__ImageUri = value; }
        }
        public bool ShouldSerializeImageUri()
        {
            return __pbn__ImageUri != null;
        }
        public void ResetImageUri()
        {
            __pbn__ImageUri = null;
        }
        private string __pbn__ImageUri;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TranscodedPicture : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TranscodedPicture()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"target_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TargetName
        {
            get { return __pbn__TargetName ?? ""; }
            set { __pbn__TargetName = value; }
        }
        public bool ShouldSerializeTargetName()
        {
            return __pbn__TargetName != null;
        }
        public void ResetTargetName()
        {
            __pbn__TargetName = null;
        }
        private string __pbn__TargetName;

        [global::ProtoBuf.ProtoMember(2, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri
        {
            get { return __pbn__Uri ?? ""; }
            set { __pbn__Uri = value; }
        }
        public bool ShouldSerializeUri()
        {
            return __pbn__Uri != null;
        }
        public void ResetUri()
        {
            __pbn__Uri = null;
        }
        private string __pbn__Uri;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlaylistAnnotation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlaylistAnnotation()
        {
            TranscodedPictures = new global::System.Collections.Generic.List<TranscodedPicture>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return __pbn__Description ?? ""; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription()
        {
            return __pbn__Description != null;
        }
        public void ResetDescription()
        {
            __pbn__Description = null;
        }
        private string __pbn__Description;

        [global::ProtoBuf.ProtoMember(2, Name = @"picture")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Picture
        {
            get { return __pbn__Picture ?? ""; }
            set { __pbn__Picture = value; }
        }
        public bool ShouldSerializePicture()
        {
            return __pbn__Picture != null;
        }
        public void ResetPicture()
        {
            __pbn__Picture = null;
        }
        private string __pbn__Picture;

        [global::ProtoBuf.ProtoMember(3, Name = @"deprecated_render_features")]
        [global::System.ComponentModel.DefaultValue(RenderFeatures.NormalFeatures)]
        [global::System.Obsolete]
        public RenderFeatures DeprecatedRenderFeatures
        {
            get { return __pbn__DeprecatedRenderFeatures ?? RenderFeatures.NormalFeatures; }
            set { __pbn__DeprecatedRenderFeatures = value; }
        }
        public bool ShouldSerializeDeprecatedRenderFeatures()
        {
            return __pbn__DeprecatedRenderFeatures != null;
        }
        public void ResetDeprecatedRenderFeatures()
        {
            __pbn__DeprecatedRenderFeatures = null;
        }
        private RenderFeatures? __pbn__DeprecatedRenderFeatures;

        [global::ProtoBuf.ProtoMember(4, Name = @"transcoded_picture")]
        public global::System.Collections.Generic.List<TranscodedPicture> TranscodedPictures { get; private set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"is_abuse_reporting_enabled")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool IsAbuseReportingEnabled
        {
            get { return __pbn__IsAbuseReportingEnabled ?? true; }
            set { __pbn__IsAbuseReportingEnabled = value; }
        }
        public bool ShouldSerializeIsAbuseReportingEnabled()
        {
            return __pbn__IsAbuseReportingEnabled != null;
        }
        public void ResetIsAbuseReportingEnabled()
        {
            __pbn__IsAbuseReportingEnabled = null;
        }
        private bool? __pbn__IsAbuseReportingEnabled;

        [global::ProtoBuf.ProtoMember(7, Name = @"abuse_report_state")]
        [global::System.ComponentModel.DefaultValue(AbuseReportState.Ok)]
        public AbuseReportState AbuseReportState
        {
            get { return __pbn__AbuseReportState ?? AbuseReportState.Ok; }
            set { __pbn__AbuseReportState = value; }
        }
        public bool ShouldSerializeAbuseReportState()
        {
            return __pbn__AbuseReportState != null;
        }
        public void ResetAbuseReportState()
        {
            __pbn__AbuseReportState = null;
        }
        private AbuseReportState? __pbn__AbuseReportState;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum RenderFeatures
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NORMAL_FEATURES")]
        NormalFeatures = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"EXTENDED_FEATURES")]
        ExtendedFeatures = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AbuseReportState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"OK")]
        Ok = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TAKEN_DOWN")]
        TakenDown = 1,
    }

}

#pragma warning restore 0612, 1591, 3021
