// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: playlist4_external.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.playlist4.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Item : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Item()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri", IsRequired = true)]
        public string Uri { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"attributes")]
        public ItemAttributes Attributes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MetaItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MetaItem()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"revision")]
        public byte[] Revision
        {
            get { return __pbn__Revision; }
            set { __pbn__Revision = value; }
        }
        public bool ShouldSerializeRevision()
        {
            return __pbn__Revision != null;
        }
        public void ResetRevision()
        {
            __pbn__Revision = null;
        }
        private byte[] __pbn__Revision;

        [global::ProtoBuf.ProtoMember(2, Name = @"attributes")]
        public ListAttributes Attributes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"length")]
        public int Length
        {
            get { return __pbn__Length.GetValueOrDefault(); }
            set { __pbn__Length = value; }
        }
        public bool ShouldSerializeLength()
        {
            return __pbn__Length != null;
        }
        public void ResetLength()
        {
            __pbn__Length = null;
        }
        private int? __pbn__Length;

        [global::ProtoBuf.ProtoMember(4, Name = @"timestamp")]
        public long Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp()
        {
            return __pbn__Timestamp != null;
        }
        public void ResetTimestamp()
        {
            __pbn__Timestamp = null;
        }
        private long? __pbn__Timestamp;

        [global::ProtoBuf.ProtoMember(5, Name = @"owner_username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OwnerUsername
        {
            get { return __pbn__OwnerUsername ?? ""; }
            set { __pbn__OwnerUsername = value; }
        }
        public bool ShouldSerializeOwnerUsername()
        {
            return __pbn__OwnerUsername != null;
        }
        public void ResetOwnerUsername()
        {
            __pbn__OwnerUsername = null;
        }
        private string __pbn__OwnerUsername;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListItems : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ListItems()
        {
            Items = new global::System.Collections.Generic.List<Item>();
            MetaItems = new global::System.Collections.Generic.List<MetaItem>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public int Pos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"truncated", IsRequired = true)]
        public bool Truncated { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"items")]
        public global::System.Collections.Generic.List<Item> Items { get; private set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"meta_items")]
        public global::System.Collections.Generic.List<MetaItem> MetaItems { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FormatListAttribute : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public FormatListAttribute()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key
        {
            get { return __pbn__Key ?? ""; }
            set { __pbn__Key = value; }
        }
        public bool ShouldSerializeKey()
        {
            return __pbn__Key != null;
        }
        public void ResetKey()
        {
            __pbn__Key = null;
        }
        private string __pbn__Key;

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value
        {
            get { return __pbn__Value ?? ""; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue()
        {
            return __pbn__Value != null;
        }
        public void ResetValue()
        {
            __pbn__Value = null;
        }
        private string __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ListAttributes()
        {
            FormatAttributes = new global::System.Collections.Generic.List<FormatListAttribute>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName()
        {
            return __pbn__Name != null;
        }
        public void ResetName()
        {
            __pbn__Name = null;
        }
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return __pbn__Description ?? ""; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription()
        {
            return __pbn__Description != null;
        }
        public void ResetDescription()
        {
            __pbn__Description = null;
        }
        private string __pbn__Description;

        [global::ProtoBuf.ProtoMember(3, Name = @"picture")]
        public byte[] Picture
        {
            get { return __pbn__Picture; }
            set { __pbn__Picture = value; }
        }
        public bool ShouldSerializePicture()
        {
            return __pbn__Picture != null;
        }
        public void ResetPicture()
        {
            __pbn__Picture = null;
        }
        private byte[] __pbn__Picture;

        [global::ProtoBuf.ProtoMember(4, Name = @"collaborative")]
        public bool Collaborative
        {
            get { return __pbn__Collaborative.GetValueOrDefault(); }
            set { __pbn__Collaborative = value; }
        }
        public bool ShouldSerializeCollaborative()
        {
            return __pbn__Collaborative != null;
        }
        public void ResetCollaborative()
        {
            __pbn__Collaborative = null;
        }
        private bool? __pbn__Collaborative;

        [global::ProtoBuf.ProtoMember(5, Name = @"pl3_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pl3Version
        {
            get { return __pbn__Pl3Version ?? ""; }
            set { __pbn__Pl3Version = value; }
        }
        public bool ShouldSerializePl3Version()
        {
            return __pbn__Pl3Version != null;
        }
        public void ResetPl3Version()
        {
            __pbn__Pl3Version = null;
        }
        private string __pbn__Pl3Version;

        [global::ProtoBuf.ProtoMember(6, Name = @"deleted_by_owner")]
        public bool DeletedByOwner
        {
            get { return __pbn__DeletedByOwner.GetValueOrDefault(); }
            set { __pbn__DeletedByOwner = value; }
        }
        public bool ShouldSerializeDeletedByOwner()
        {
            return __pbn__DeletedByOwner != null;
        }
        public void ResetDeletedByOwner()
        {
            __pbn__DeletedByOwner = null;
        }
        private bool? __pbn__DeletedByOwner;

        [global::ProtoBuf.ProtoMember(10, Name = @"client_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientId
        {
            get { return __pbn__ClientId ?? ""; }
            set { __pbn__ClientId = value; }
        }
        public bool ShouldSerializeClientId()
        {
            return __pbn__ClientId != null;
        }
        public void ResetClientId()
        {
            __pbn__ClientId = null;
        }
        private string __pbn__ClientId;

        [global::ProtoBuf.ProtoMember(11, Name = @"format")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Format
        {
            get { return __pbn__Format ?? ""; }
            set { __pbn__Format = value; }
        }
        public bool ShouldSerializeFormat()
        {
            return __pbn__Format != null;
        }
        public void ResetFormat()
        {
            __pbn__Format = null;
        }
        private string __pbn__Format;

        [global::ProtoBuf.ProtoMember(12, Name = @"format_attributes")]
        public global::System.Collections.Generic.List<FormatListAttribute> FormatAttributes { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ItemAttributes()
        {
            FormatAttributes = new global::System.Collections.Generic.List<FormatListAttribute>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"added_by")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AddedBy
        {
            get { return __pbn__AddedBy ?? ""; }
            set { __pbn__AddedBy = value; }
        }
        public bool ShouldSerializeAddedBy()
        {
            return __pbn__AddedBy != null;
        }
        public void ResetAddedBy()
        {
            __pbn__AddedBy = null;
        }
        private string __pbn__AddedBy;

        [global::ProtoBuf.ProtoMember(2, Name = @"timestamp")]
        public long Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp()
        {
            return __pbn__Timestamp != null;
        }
        public void ResetTimestamp()
        {
            __pbn__Timestamp = null;
        }
        private long? __pbn__Timestamp;

        [global::ProtoBuf.ProtoMember(9, Name = @"seen_at")]
        public long SeenAt
        {
            get { return __pbn__SeenAt.GetValueOrDefault(); }
            set { __pbn__SeenAt = value; }
        }
        public bool ShouldSerializeSeenAt()
        {
            return __pbn__SeenAt != null;
        }
        public void ResetSeenAt()
        {
            __pbn__SeenAt = null;
        }
        private long? __pbn__SeenAt;

        [global::ProtoBuf.ProtoMember(10, Name = @"public")]
        public bool Public
        {
            get { return __pbn__Public.GetValueOrDefault(); }
            set { __pbn__Public = value; }
        }
        public bool ShouldSerializePublic()
        {
            return __pbn__Public != null;
        }
        public void ResetPublic()
        {
            __pbn__Public = null;
        }
        private bool? __pbn__Public;

        [global::ProtoBuf.ProtoMember(11, Name = @"format_attributes")]
        public global::System.Collections.Generic.List<FormatListAttribute> FormatAttributes { get; private set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"item_id")]
        public byte[] ItemId
        {
            get { return __pbn__ItemId; }
            set { __pbn__ItemId = value; }
        }
        public bool ShouldSerializeItemId()
        {
            return __pbn__ItemId != null;
        }
        public void ResetItemId()
        {
            __pbn__ItemId = null;
        }
        private byte[] __pbn__ItemId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Add : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Add()
        {
            Items = new global::System.Collections.Generic.List<Item>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"from_index")]
        public int FromIndex
        {
            get { return __pbn__FromIndex.GetValueOrDefault(); }
            set { __pbn__FromIndex = value; }
        }
        public bool ShouldSerializeFromIndex()
        {
            return __pbn__FromIndex != null;
        }
        public void ResetFromIndex()
        {
            __pbn__FromIndex = null;
        }
        private int? __pbn__FromIndex;

        [global::ProtoBuf.ProtoMember(2, Name = @"items")]
        public global::System.Collections.Generic.List<Item> Items { get; private set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"add_last")]
        public bool AddLast
        {
            get { return __pbn__AddLast.GetValueOrDefault(); }
            set { __pbn__AddLast = value; }
        }
        public bool ShouldSerializeAddLast()
        {
            return __pbn__AddLast != null;
        }
        public void ResetAddLast()
        {
            __pbn__AddLast = null;
        }
        private bool? __pbn__AddLast;

        [global::ProtoBuf.ProtoMember(5, Name = @"add_first")]
        public bool AddFirst
        {
            get { return __pbn__AddFirst.GetValueOrDefault(); }
            set { __pbn__AddFirst = value; }
        }
        public bool ShouldSerializeAddFirst()
        {
            return __pbn__AddFirst != null;
        }
        public void ResetAddFirst()
        {
            __pbn__AddFirst = null;
        }
        private bool? __pbn__AddFirst;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Rem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Rem()
        {
            Items = new global::System.Collections.Generic.List<Item>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"from_index")]
        public int FromIndex
        {
            get { return __pbn__FromIndex.GetValueOrDefault(); }
            set { __pbn__FromIndex = value; }
        }
        public bool ShouldSerializeFromIndex()
        {
            return __pbn__FromIndex != null;
        }
        public void ResetFromIndex()
        {
            __pbn__FromIndex = null;
        }
        private int? __pbn__FromIndex;

        [global::ProtoBuf.ProtoMember(2, Name = @"length")]
        public int Length
        {
            get { return __pbn__Length.GetValueOrDefault(); }
            set { __pbn__Length = value; }
        }
        public bool ShouldSerializeLength()
        {
            return __pbn__Length != null;
        }
        public void ResetLength()
        {
            __pbn__Length = null;
        }
        private int? __pbn__Length;

        [global::ProtoBuf.ProtoMember(3, Name = @"items")]
        public global::System.Collections.Generic.List<Item> Items { get; private set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"items_as_key")]
        public bool ItemsAsKey
        {
            get { return __pbn__ItemsAsKey.GetValueOrDefault(); }
            set { __pbn__ItemsAsKey = value; }
        }
        public bool ShouldSerializeItemsAsKey()
        {
            return __pbn__ItemsAsKey != null;
        }
        public void ResetItemsAsKey()
        {
            __pbn__ItemsAsKey = null;
        }
        private bool? __pbn__ItemsAsKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Mov : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Mov()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"from_index", IsRequired = true)]
        public int FromIndex { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"length", IsRequired = true)]
        public int Length { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"to_index", IsRequired = true)]
        public int ToIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemAttributesPartialState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ItemAttributesPartialState()
        {
            NoValues = new global::System.Collections.Generic.List<ItemAttributeKind>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"values", IsRequired = true)]
        public ItemAttributes Values { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"no_value")]
        public global::System.Collections.Generic.List<ItemAttributeKind> NoValues { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListAttributesPartialState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ListAttributesPartialState()
        {
            NoValues = new global::System.Collections.Generic.List<ListAttributeKind>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"values", IsRequired = true)]
        public ListAttributes Values { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"no_value")]
        public global::System.Collections.Generic.List<ListAttributeKind> NoValues { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateItemAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UpdateItemAttributes()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"index", IsRequired = true)]
        public int Index { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"new_attributes", IsRequired = true)]
        public ItemAttributesPartialState NewAttributes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"old_attributes")]
        public ItemAttributesPartialState OldAttributes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateListAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UpdateListAttributes()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"new_attributes", IsRequired = true)]
        public ListAttributesPartialState NewAttributes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"old_attributes")]
        public ListAttributesPartialState OldAttributes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Op : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Op()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Kind kind { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"add")]
        public Add Add { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"rem")]
        public Rem Rem { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"mov")]
        public Mov Mov { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"update_item_attributes")]
        public UpdateItemAttributes UpdateItemAttributes { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"update_list_attributes")]
        public UpdateListAttributes UpdateListAttributes { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Kind
        {
            [global::ProtoBuf.ProtoEnum(Name = @"KIND_UNKNOWN")]
            KindUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ADD")]
            Add = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"REM")]
            Rem = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MOV")]
            Mov = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"UPDATE_ITEM_ATTRIBUTES")]
            UpdateItemAttributes = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"UPDATE_LIST_ATTRIBUTES")]
            UpdateListAttributes = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OpList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public OpList()
        {
            Ops = new global::System.Collections.Generic.List<Op>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"ops")]
        public global::System.Collections.Generic.List<Op> Ops { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ChangeInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        [global::System.ComponentModel.DefaultValue("")]
        public string User
        {
            get { return __pbn__User ?? ""; }
            set { __pbn__User = value; }
        }
        public bool ShouldSerializeUser()
        {
            return __pbn__User != null;
        }
        public void ResetUser()
        {
            __pbn__User = null;
        }
        private string __pbn__User;

        [global::ProtoBuf.ProtoMember(2, Name = @"timestamp")]
        public long Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp()
        {
            return __pbn__Timestamp != null;
        }
        public void ResetTimestamp()
        {
            __pbn__Timestamp = null;
        }
        private long? __pbn__Timestamp;

        [global::ProtoBuf.ProtoMember(3, Name = @"admin")]
        public bool Admin
        {
            get { return __pbn__Admin.GetValueOrDefault(); }
            set { __pbn__Admin = value; }
        }
        public bool ShouldSerializeAdmin()
        {
            return __pbn__Admin != null;
        }
        public void ResetAdmin()
        {
            __pbn__Admin = null;
        }
        private bool? __pbn__Admin;

        [global::ProtoBuf.ProtoMember(4, Name = @"undo")]
        public bool Undo
        {
            get { return __pbn__Undo.GetValueOrDefault(); }
            set { __pbn__Undo = value; }
        }
        public bool ShouldSerializeUndo()
        {
            return __pbn__Undo != null;
        }
        public void ResetUndo()
        {
            __pbn__Undo = null;
        }
        private bool? __pbn__Undo;

        [global::ProtoBuf.ProtoMember(5, Name = @"redo")]
        public bool Redo
        {
            get { return __pbn__Redo.GetValueOrDefault(); }
            set { __pbn__Redo = value; }
        }
        public bool ShouldSerializeRedo()
        {
            return __pbn__Redo != null;
        }
        public void ResetRedo()
        {
            __pbn__Redo = null;
        }
        private bool? __pbn__Redo;

        [global::ProtoBuf.ProtoMember(6, Name = @"merge")]
        public bool Merge
        {
            get { return __pbn__Merge.GetValueOrDefault(); }
            set { __pbn__Merge = value; }
        }
        public bool ShouldSerializeMerge()
        {
            return __pbn__Merge != null;
        }
        public void ResetMerge()
        {
            __pbn__Merge = null;
        }
        private bool? __pbn__Merge;

        [global::ProtoBuf.ProtoMember(7, Name = @"compressed")]
        public bool Compressed
        {
            get { return __pbn__Compressed.GetValueOrDefault(); }
            set { __pbn__Compressed = value; }
        }
        public bool ShouldSerializeCompressed()
        {
            return __pbn__Compressed != null;
        }
        public void ResetCompressed()
        {
            __pbn__Compressed = null;
        }
        private bool? __pbn__Compressed;

        [global::ProtoBuf.ProtoMember(8, Name = @"migration")]
        public bool Migration
        {
            get { return __pbn__Migration.GetValueOrDefault(); }
            set { __pbn__Migration = value; }
        }
        public bool ShouldSerializeMigration()
        {
            return __pbn__Migration != null;
        }
        public void ResetMigration()
        {
            __pbn__Migration = null;
        }
        private bool? __pbn__Migration;

        [global::ProtoBuf.ProtoMember(9, Name = @"split_id")]
        public int SplitId
        {
            get { return __pbn__SplitId.GetValueOrDefault(); }
            set { __pbn__SplitId = value; }
        }
        public bool ShouldSerializeSplitId()
        {
            return __pbn__SplitId != null;
        }
        public void ResetSplitId()
        {
            __pbn__SplitId = null;
        }
        private int? __pbn__SplitId;

        [global::ProtoBuf.ProtoMember(10, Name = @"source")]
        public SourceInfo Source { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SourceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SourceInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(Client.ClientUnknown)]
        public Client client
        {
            get { return __pbn__client ?? Client.ClientUnknown; }
            set { __pbn__client = value; }
        }
        public bool ShouldSerializeclient()
        {
            return __pbn__client != null;
        }
        public void Resetclient()
        {
            __pbn__client = null;
        }
        private Client? __pbn__client;

        [global::ProtoBuf.ProtoMember(3, Name = @"app")]
        [global::System.ComponentModel.DefaultValue("")]
        public string App
        {
            get { return __pbn__App ?? ""; }
            set { __pbn__App = value; }
        }
        public bool ShouldSerializeApp()
        {
            return __pbn__App != null;
        }
        public void ResetApp()
        {
            __pbn__App = null;
        }
        private string __pbn__App;

        [global::ProtoBuf.ProtoMember(4, Name = @"source")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source
        {
            get { return __pbn__Source ?? ""; }
            set { __pbn__Source = value; }
        }
        public bool ShouldSerializeSource()
        {
            return __pbn__Source != null;
        }
        public void ResetSource()
        {
            __pbn__Source = null;
        }
        private string __pbn__Source;

        [global::ProtoBuf.ProtoMember(5, Name = @"version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Version
        {
            get { return __pbn__Version ?? ""; }
            set { __pbn__Version = value; }
        }
        public bool ShouldSerializeVersion()
        {
            return __pbn__Version != null;
        }
        public void ResetVersion()
        {
            __pbn__Version = null;
        }
        private string __pbn__Version;

        [global::ProtoBuf.ProtoContract()]
        public enum Client
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_UNKNOWN")]
            ClientUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_HERMES")]
            NativeHermes = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CLIENT")]
            Client = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"PYTHON")]
            Python = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"JAVA")]
            Java = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"WEBPLAYER")]
            Webplayer = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"LIBSPOTIFY")]
            Libspotify = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Delta : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Delta()
        {
            Ops = new global::System.Collections.Generic.List<Op>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"base_version")]
        public byte[] BaseVersion
        {
            get { return __pbn__BaseVersion; }
            set { __pbn__BaseVersion = value; }
        }
        public bool ShouldSerializeBaseVersion()
        {
            return __pbn__BaseVersion != null;
        }
        public void ResetBaseVersion()
        {
            __pbn__BaseVersion = null;
        }
        private byte[] __pbn__BaseVersion;

        [global::ProtoBuf.ProtoMember(2, Name = @"ops")]
        public global::System.Collections.Generic.List<Op> Ops { get; private set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"info")]
        public ChangeInfo Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Diff : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Diff()
        {
            Ops = new global::System.Collections.Generic.List<Op>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"from_revision", IsRequired = true)]
        public byte[] FromRevision { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ops")]
        public global::System.Collections.Generic.List<Op> Ops { get; private set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"to_revision", IsRequired = true)]
        public byte[] ToRevision { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListChanges : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ListChanges()
        {
            Deltas = new global::System.Collections.Generic.List<Delta>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"base_revision")]
        public byte[] BaseRevision
        {
            get { return __pbn__BaseRevision; }
            set { __pbn__BaseRevision = value; }
        }
        public bool ShouldSerializeBaseRevision()
        {
            return __pbn__BaseRevision != null;
        }
        public void ResetBaseRevision()
        {
            __pbn__BaseRevision = null;
        }
        private byte[] __pbn__BaseRevision;

        [global::ProtoBuf.ProtoMember(2, Name = @"deltas")]
        public global::System.Collections.Generic.List<Delta> Deltas { get; private set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"want_resulting_revisions")]
        public bool WantResultingRevisions
        {
            get { return __pbn__WantResultingRevisions.GetValueOrDefault(); }
            set { __pbn__WantResultingRevisions = value; }
        }
        public bool ShouldSerializeWantResultingRevisions()
        {
            return __pbn__WantResultingRevisions != null;
        }
        public void ResetWantResultingRevisions()
        {
            __pbn__WantResultingRevisions = null;
        }
        private bool? __pbn__WantResultingRevisions;

        [global::ProtoBuf.ProtoMember(4, Name = @"want_sync_result")]
        public bool WantSyncResult
        {
            get { return __pbn__WantSyncResult.GetValueOrDefault(); }
            set { __pbn__WantSyncResult = value; }
        }
        public bool ShouldSerializeWantSyncResult()
        {
            return __pbn__WantSyncResult != null;
        }
        public void ResetWantSyncResult()
        {
            __pbn__WantSyncResult = null;
        }
        private bool? __pbn__WantSyncResult;

        [global::ProtoBuf.ProtoMember(6, Name = @"nonces")]
        public long[] Nonces { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SelectedListContent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SelectedListContent()
        {
            ResultingRevisions = new global::System.Collections.Generic.List<byte[]>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"revision")]
        public byte[] Revision
        {
            get { return __pbn__Revision; }
            set { __pbn__Revision = value; }
        }
        public bool ShouldSerializeRevision()
        {
            return __pbn__Revision != null;
        }
        public void ResetRevision()
        {
            __pbn__Revision = null;
        }
        private byte[] __pbn__Revision;

        [global::ProtoBuf.ProtoMember(2, Name = @"length")]
        public int Length
        {
            get { return __pbn__Length.GetValueOrDefault(); }
            set { __pbn__Length = value; }
        }
        public bool ShouldSerializeLength()
        {
            return __pbn__Length != null;
        }
        public void ResetLength()
        {
            __pbn__Length = null;
        }
        private int? __pbn__Length;

        [global::ProtoBuf.ProtoMember(3, Name = @"attributes")]
        public ListAttributes Attributes { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"contents")]
        public ListItems Contents { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"diff")]
        public Diff Diff { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"sync_result")]
        public Diff SyncResult { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"resulting_revisions")]
        public global::System.Collections.Generic.List<byte[]> ResultingRevisions { get; private set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"multiple_heads")]
        public bool MultipleHeads
        {
            get { return __pbn__MultipleHeads.GetValueOrDefault(); }
            set { __pbn__MultipleHeads = value; }
        }
        public bool ShouldSerializeMultipleHeads()
        {
            return __pbn__MultipleHeads != null;
        }
        public void ResetMultipleHeads()
        {
            __pbn__MultipleHeads = null;
        }
        private bool? __pbn__MultipleHeads;

        [global::ProtoBuf.ProtoMember(10, Name = @"up_to_date")]
        public bool UpToDate
        {
            get { return __pbn__UpToDate.GetValueOrDefault(); }
            set { __pbn__UpToDate = value; }
        }
        public bool ShouldSerializeUpToDate()
        {
            return __pbn__UpToDate != null;
        }
        public void ResetUpToDate()
        {
            __pbn__UpToDate = null;
        }
        private bool? __pbn__UpToDate;

        [global::ProtoBuf.ProtoMember(14, Name = @"nonces")]
        public long[] Nonces { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"timestamp")]
        public long Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp()
        {
            return __pbn__Timestamp != null;
        }
        public void ResetTimestamp()
        {
            __pbn__Timestamp = null;
        }
        private long? __pbn__Timestamp;

        [global::ProtoBuf.ProtoMember(16, Name = @"owner_username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OwnerUsername
        {
            get { return __pbn__OwnerUsername ?? ""; }
            set { __pbn__OwnerUsername = value; }
        }
        public bool ShouldSerializeOwnerUsername()
        {
            return __pbn__OwnerUsername != null;
        }
        public void ResetOwnerUsername()
        {
            __pbn__OwnerUsername = null;
        }
        private string __pbn__OwnerUsername;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateListReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public CreateListReply()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri", IsRequired = true)]
        public byte[] Uri { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"revision")]
        public byte[] Revision
        {
            get { return __pbn__Revision; }
            set { __pbn__Revision = value; }
        }
        public bool ShouldSerializeRevision()
        {
            return __pbn__Revision != null;
        }
        public void ResetRevision()
        {
            __pbn__Revision = null;
        }
        private byte[] __pbn__Revision;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModifyReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ModifyReply()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri", IsRequired = true)]
        public byte[] Uri { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"revision")]
        public byte[] Revision
        {
            get { return __pbn__Revision; }
            set { __pbn__Revision = value; }
        }
        public bool ShouldSerializeRevision()
        {
            return __pbn__Revision != null;
        }
        public void ResetRevision()
        {
            __pbn__Revision = null;
        }
        private byte[] __pbn__Revision;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SubscribeRequest()
        {
            Ures = new global::System.Collections.Generic.List<byte[]>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uris")]
        public global::System.Collections.Generic.List<byte[]> Ures { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsubscribeRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UnsubscribeRequest()
        {
            Ures = new global::System.Collections.Generic.List<byte[]>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uris")]
        public global::System.Collections.Generic.List<byte[]> Ures { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlaylistModificationInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlaylistModificationInfo()
        {
            Ops = new global::System.Collections.Generic.List<Op>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        public byte[] Uri
        {
            get { return __pbn__Uri; }
            set { __pbn__Uri = value; }
        }
        public bool ShouldSerializeUri()
        {
            return __pbn__Uri != null;
        }
        public void ResetUri()
        {
            __pbn__Uri = null;
        }
        private byte[] __pbn__Uri;

        [global::ProtoBuf.ProtoMember(2, Name = @"new_revision")]
        public byte[] NewRevision
        {
            get { return __pbn__NewRevision; }
            set { __pbn__NewRevision = value; }
        }
        public bool ShouldSerializeNewRevision()
        {
            return __pbn__NewRevision != null;
        }
        public void ResetNewRevision()
        {
            __pbn__NewRevision = null;
        }
        private byte[] __pbn__NewRevision;

        [global::ProtoBuf.ProtoMember(3, Name = @"parent_revision")]
        public byte[] ParentRevision
        {
            get { return __pbn__ParentRevision; }
            set { __pbn__ParentRevision = value; }
        }
        public bool ShouldSerializeParentRevision()
        {
            return __pbn__ParentRevision != null;
        }
        public void ResetParentRevision()
        {
            __pbn__ParentRevision = null;
        }
        private byte[] __pbn__ParentRevision;

        [global::ProtoBuf.ProtoMember(4, Name = @"ops")]
        public global::System.Collections.Generic.List<Op> Ops { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum ListAttributeKind
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_UNKNOWN")]
        ListUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_NAME")]
        ListName = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_DESCRIPTION")]
        ListDescription = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_PICTURE")]
        ListPicture = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_COLLABORATIVE")]
        ListCollaborative = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_PL3_VERSION")]
        ListPl3Version = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_DELETED_BY_OWNER")]
        ListDeletedByOwner = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_CLIENT_ID")]
        ListClientId = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_FORMAT")]
        ListFormat = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"LIST_FORMAT_ATTRIBUTES")]
        ListFormatAttributes = 12,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ItemAttributeKind
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_UNKNOWN")]
        ItemUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_ADDED_BY")]
        ItemAddedBy = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_TIMESTAMP")]
        ItemTimestamp = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_SEEN_AT")]
        ItemSeenAt = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_PUBLIC")]
        ItemPublic = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_FORMAT_ATTRIBUTES")]
        ItemFormatAttributes = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_ID")]
        ItemId = 12,
    }

}

#pragma warning restore 0612, 1591, 3021
