// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: pubsub.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Spotify
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Subscription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri
        {
            get { return __pbn__Uri ?? ""; }
            set { __pbn__Uri = value; }
        }
        public bool ShouldSerializeUri() => __pbn__Uri != null;
        public void ResetUri() => __pbn__Uri = null;
        private string __pbn__Uri;

        [global::ProtoBuf.ProtoMember(2, Name = @"expiry")]
        public int Expiry
        {
            get { return __pbn__Expiry.GetValueOrDefault(); }
            set { __pbn__Expiry = value; }
        }
        public bool ShouldSerializeExpiry() => __pbn__Expiry != null;
        public void ResetExpiry() => __pbn__Expiry = null;
        private int? __pbn__Expiry;

        [global::ProtoBuf.ProtoMember(3, Name = @"status_code")]
        public int StatusCode
        {
            get { return __pbn__StatusCode.GetValueOrDefault(); }
            set { __pbn__StatusCode = value; }
        }
        public bool ShouldSerializeStatusCode() => __pbn__StatusCode != null;
        public void ResetStatusCode() => __pbn__StatusCode = null;
        private int? __pbn__StatusCode;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
