// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: queue.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.player.proto.transfer
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Queue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Queue()
        {
            Tracks = new global::System.Collections.Generic.List<global::spotify.player.proto.ContextTrack>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"tracks")]
        public global::System.Collections.Generic.List<global::spotify.player.proto.ContextTrack> Tracks { get; private set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"is_playing_queue")]
        public bool IsPlayingQueue
        {
            get { return __pbn__IsPlayingQueue.GetValueOrDefault(); }
            set { __pbn__IsPlayingQueue = value; }
        }
        public bool ShouldSerializeIsPlayingQueue()
        {
            return __pbn__IsPlayingQueue != null;
        }
        public void ResetIsPlayingQueue()
        {
            __pbn__IsPlayingQueue = null;
        }
        private bool? __pbn__IsPlayingQueue;

    }

}

#pragma warning restore 0612, 1591, 3021
