// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: queue.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.player.proto.transfer
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Queue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tracks")]
        public global::System.Collections.Generic.List<global::spotify.player.proto.ContextTrack> Tracks { get; } = new global::System.Collections.Generic.List<global::spotify.player.proto.ContextTrack>();

        [global::ProtoBuf.ProtoMember(2, Name = @"is_playing_queue")]
        public bool IsPlayingQueue
        {
            get { return __pbn__IsPlayingQueue.GetValueOrDefault(); }
            set { __pbn__IsPlayingQueue = value; }
        }
        public bool ShouldSerializeIsPlayingQueue() => __pbn__IsPlayingQueue != null;
        public void ResetIsPlayingQueue() => __pbn__IsPlayingQueue = null;
        private bool? __pbn__IsPlayingQueue;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
