// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: session.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.player.proto.transfer
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Session : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Session()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"play_origin")]
        public global::spotify.player.proto.PlayOrigin PlayOrigin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"context")]
        public global::spotify.player.proto.Context Context { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"current_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CurrentUid
        {
            get { return __pbn__CurrentUid ?? ""; }
            set { __pbn__CurrentUid = value; }
        }
        public bool ShouldSerializeCurrentUid()
        {
            return __pbn__CurrentUid != null;
        }
        public void ResetCurrentUid()
        {
            __pbn__CurrentUid = null;
        }
        private string __pbn__CurrentUid;

        [global::ProtoBuf.ProtoMember(4, Name = @"option_overrides")]
        public global::spotify.player.proto.ContextPlayerOptionOverrides OptionOverrides { get; set; }

    }

}

#pragma warning restore 0612, 1591, 3021
