// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: session.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.player.proto.transfer
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Session : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"play_origin")]
        public global::spotify.player.proto.PlayOrigin PlayOrigin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"context")]
        public global::spotify.player.proto.Context Context { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"current_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CurrentUid
        {
            get { return __pbn__CurrentUid ?? ""; }
            set { __pbn__CurrentUid = value; }
        }
        public bool ShouldSerializeCurrentUid() => __pbn__CurrentUid != null;
        public void ResetCurrentUid() => __pbn__CurrentUid = null;
        private string __pbn__CurrentUid;

        [global::ProtoBuf.ProtoMember(4, Name = @"option_overrides")]
        public global::spotify.player.proto.ContextPlayerOptionOverrides OptionOverrides { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
