// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: storage-resolve.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.download.proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StorageResolveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Result result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cdnurl")]
        public global::System.Collections.Generic.List<string> Cdnurls { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"fileid")]
        public byte[] Fileid { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Result
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CDN")]
            Cdn = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"STORAGE")]
            Storage = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"RESTRICTED")]
            Restricted = 3,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
