// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: transfer_state.proto

#pragma warning disable 0612, 1591, 3021
namespace spotify.player.proto.transfer
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TransferState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TransferState()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, Name = @"options")]
        public global::spotify.player.proto.ContextPlayerOptions Options { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"playback")]
        public Playback Playback { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"current_session")]
        public Session CurrentSession { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"queue")]
        public Queue Queue { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"creation_timestamp")]
        public long CreationTimestamp
        {
            get { return __pbn__CreationTimestamp.GetValueOrDefault(); }
            set { __pbn__CreationTimestamp = value; }
        }
        public bool ShouldSerializeCreationTimestamp()
        {
            return __pbn__CreationTimestamp != null;
        }
        public void ResetCreationTimestamp()
        {
            __pbn__CreationTimestamp = null;
        }
        private long? __pbn__CreationTimestamp;

    }

}

#pragma warning restore 0612, 1591, 3021
