// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: credentials.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.login5.v3.credentials
{

    [global::ProtoBuf.ProtoContract()]
    public partial class StoredCredential : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Username { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Password : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string password { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"padding")]
        public byte[] Padding { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FacebookAccessToken : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"fb_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FbUid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"access_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccessToken { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OneTimeToken : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ParentChildCredential : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"child_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"parent_stored_credential")]
        public StoredCredential ParentStoredCredential { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppleSignInCredential : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"auth_code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AuthCode { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"redirect_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RedirectUri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"bundle_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BundleId { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
