// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: identifiers.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace spotify.login5.v3.identifiers
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PhoneNumber : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Number { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"iso_country_code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IsoCountryCode { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"country_calling_code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CountryCallingCode { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
